### ISSUE TITLE
VCU118 fails to boot if using two cores

### ISSUE THREAD

**Issue by michael-etzkorn** [ucb-bar/chipyard#1009]
**Impact**: rtl|software

**Tell us about your environment:**
*Chipyard Version:* Latest
*OS:* CentOs7
*Other:* 

Generating two cores instead of one for RocketVCU118 config. 

**What is the current behavior?**

SD card errors out if using two cores. Does not if only using one. 

**What is the expected behavior?**

SD card starts loading if two cores are used. 

**Other information**

I'm using abstract config, two big rocket cores and then the VCU118 Tweaks. The SD card errors out. If I switch back to one big rocket core, the SD card will start loading.

**Comment by michael-etzkorn** [comment]
Once we have a working solution, I or one of my teammates will submit a pull request ~

**Comment by Yuxin-Yu** [comment]
Hello, may I ask if your dual-core SOC starts normally? Can you tell me how you modified it?
