### ISSUE TITLE
Linux linker script for vcu118 location?

### ISSUE THREAD

**Issue by michael-etzkorn** [ucb-bar/chipyard#1044]
I've noticed that I get different results after a reset when running the same firmware on a prototyped design on the vcu118. It might be related to this question https://github.com/ucb-bar/chipyard/issues/1012 . It seems like some static data retains its value between runs. I was wondering if this had something to do with DDR's addressing. I noticed there's only 26 bits for addressing in some of the buffers that connect to the vcu118 mig. This would mean 32 byte aligned sections might be needed. I'm looking into how Linux is running on the board without reset issues. Does anyone know where I might be able to find the linker script used when building linux? I assume it'd be somewhere in `chipyard/software`? If so, it doesn't seem to have a `.lds` extension.

**Comment by abejgonzalez** [comment]
All Linux-related collateral is part of FireMarshal (the kernel and buildroot). This is found in the `boards` area.
