### ISSUE TITLE
VCU118：I can't boot boom on VCU118 

### ISSUE THREAD

**Issue by pig-pig-yang** [ucb-bar/chipyard#1059]
I prepared the bitstream according to the documentation and used 2020.1 Vivado to load the bitstream file. Secondly, the br-base-nodisk-flat file was generated according to the instructions. After loading the SD card, the following problems occurred in the RESET FPAG.

`INIT
CMD0
sd_cmd: timeout
ERROR
`
![image](https://user-images.githubusercontent.com/65580829/145747212-8aa5bad6-947e-4308-be8c-adfbf91a375c.png)

**Comment by michael-etzkorn** [comment]
Are you connecting a PMOD to microSD card converter to the board? The sd card is over the PMOD pins, not the sd card slot that comes with the board (that's only for the zynq system controller).

If you are using the PMOD pins, it might be some issue with the SD card. I know I had an SD card that no matter what didn't seem to be read by the FPGA bootrom.

**Comment by pig-pig-yang** [comment]
I didn't connect a PMOD to microSD card converter to the board.  What should i prepare for it?
Thank you for your reply.

**Comment by michael-etzkorn** [comment]
Yeah, the microSD card connects over PMOD pins. The relevant fpga-shells code is here https://github.com/sifive/fpga-shells/blob/f9fb9fd338e5fca2ff5116b1d01506c424280d70/src/main/scala/shell/xilinx/VCU118NewShell.scala#L56

What you'll need to do is buy a Pmod MicroSD. They cost about $10. I believe the one Diligent sells has been reliable.

**Comment by pig-pig-yang** [comment]
I had bought a microSD card connects over PMOD pins. However, It didn't turn out well.  I couldn't figure out what the problem was.
![image](https://user-images.githubusercontent.com/65580829/145924197-3001afa1-4346-4875-8355-7fe4711cd73e.png)
The terminal stops output at this point.

**Comment by pig-pig-yang** [comment]
<img width="570" alt="747d8f0238dcca66f3c5cc7f21d5906" src="https://user-images.githubusercontent.com/65580829/145995123-c9d37443-9008-41ab-bf26-a57bcd735a2c.png">

**Comment by jamesdunn** [comment]
I replied to your question on the Chipyard mailing list but will echo here. We can close this issue and continue discussion on the mailing list.

My hunch is that the SD card isn't being formatted correctly. The partitions are Apple HFS/APFS when I would expect them to be ext4. [This link](https://www.youtube.com/watch?v=_xWCz1JJwTg&t=1h50m38s) describes the process for formatting the card.

**Comment by michael-etzkorn** [comment]
> I replied to your question on the Chipyard mailing list but will echo here. We can close this issue and continue discussion on the mailing list.
> 
> My hunch is that the SD card isn't being formatted correctly. The partitions are Apple HFS/APFS when I would expect them to be ext4. [This link](https://www.youtube.com/watch?v=_xWCz1JJwTg&t=1h50m38s) describes the process for formatting the card.

These are actually the recommended file systems from [the documentation](https://chipyard.readthedocs.io/en/latest/Prototyping/VCU118.html). Unless I'm missing something in the screenshot, partitioning with the apple filesystems in this way should be readable by the FPGA bootrom. I'd have to double-check my SD cards, but I think they all use APFS for the first partition and HFS for the second partition.

**Comment by zld932** [comment]
I have the same problem with you. Have you solved it?

**Comment by Yuxin-Yu** [comment]
> I have the same problem with you. Have you solved it?

Hi,Bro.I got the samle problem.Have you solved it ?

**Comment by Yuxin-Yu** [comment]
> I have the same problem with you. Have you solved it?

I have the same problem with you. Have you solved it?

**Comment by Yuxin-Yu** [comment]
> I prepared the bitstream according to the documentation and used 2020.1 Vivado to load the bitstream file. Secondly, the br-base-nodisk-flat file was generated according to the instructions. After loading the SD card, the following problems occurred in the RESET FPAG.
> 
> `INIT CMD0 sd_cmd: timeout ERROR ` ![image](https://user-images.githubusercontent.com/65580829/145747212-8aa5bad6-947e-4308-be8c-adfbf91a375c.png)

I have the same problem with you. Have you solved it?

**Comment by pig-pig-yang** [comment]
> > I prepared the bitstream according to the documentation and used 2020.1 Vivado to load the bitstream file. Secondly, the br-base-nodisk-flat file was generated according to the instructions. After loading the SD card, the following problems occurred in the RESET FPAG.
> > `INIT CMD0 sd_cmd: timeout ERROR ` ![image](https://user-images.githubusercontent.com/65580829/145747212-8aa5bad6-947e-4308-be8c-adfbf91a375c.png)
> 
> I have the same problem with you. Have you solved it?

Whether you purchased Pmod MicroSD, as well as check your pin allocation

**Comment by pig-pig-yang** [comment]
> 

https://github.com/sifive/fpga-shells/blob/f9fb9fd338e5fca2ff5116b1d01506c424280d70/src/main/scala/shell/xilinx/VCU118NewShell.scala#L56-L61

**Comment by pig-pig-yang** [comment]
> > > I prepared the bitstream according to the documentation and used 2020.1 Vivado to load the bitstream file. Secondly, the br-base-nodisk-flat file was generated according to the instructions. After loading the SD card, the following problems occurred in the RESET FPAG.
> > > `INIT CMD0 sd_cmd: timeout ERROR ` ![image](https://user-images.githubusercontent.com/65580829/145747212-8aa5bad6-947e-4308-be8c-adfbf91a375c.png)
> > 
> > 
> > I have the same problem with you. Have you solved it?
> 
> Whether you purchased Pmod MicroSD, as well as check your pin allocation
https://github.com/sifive/fpga-shells/blob/f9fb9fd338e5fca2ff5116b1d01506c424280d70/src/main/scala/shell/xilinx/VCU118NewShell.scala#L56-L61

**Comment by leduchuybk** [comment]
@pig-pig-yang i met same problem. after i changed the pin cs and mosi on the sdcard module extension. it works. from what i saw in the code: fpga-shells/src/main/scala/shell/xilinx/SDIOOverlay.scala line 39 and 40.
`UIntToAnalog(sd_spi_cs, io.spi_dat(3), true.B)
UIntToAnalog(sd_spi_dq(0), io.spi_cs, true.B)`
they switched these pin. i do not know the reason why. but it seems that these pin are wrongly assigned

**Comment by michael-etzkorn** [comment]
It naturally will depend on your pmod sd card module. The PMOD microSD card module from Digilent works without needing to switch any pins. If you purchashed from a different vendor, check your schematic and align the pins correctly in the overlay. 

Another important point mentioned upstream: the VCU118's SD card slot is not the slot connected the SDIO (it's for some board management, it has no pins connected to the FPGA). The SD card should be connected over the female PMOD connector.

**Comment by michael-etzkorn** [comment]
Are you connecting to an SD card over the PMOD pins? The built-in sd card
slot on the vcu118 is not for the FPGA.

Did you make sure your binary starts at sector 34?

Yuxin ***@***.***>于2022年8月9日 周二上午3:25写道：

**Comment by jiayang-douding** [comment]
Hello, I also encountered the same issue when booting Linux on the VCU118. Have you resolved it? Below is the log output from my serial port.

![Image](https://github.com/user-attachments/assets/0ee0ad52-5ccb-4159-bf94-341b688a255b)

![Image](https://github.com/user-attachments/assets/d9a4322f-bf5a-4b40-9a01-e4ef36bc4caa)
