### ISSUE TITLE
About "Make"

### ISSUE THREAD

**Issue by lpppeipei** [ucb-bar/chipyard#1069]
When "Simulating The Default Example'
"To compile the example design, run make in the selected verilator or VCS directory. This will elaborate the RocketConfig in the example project."

What is  the command "make" in detail ?

And  here
"Compiling this program with make produces a gcd.riscv executable."  So how  can I get a gcd.riscv file "
Then 
"Now with all of that done, we can go ahead and run our simulation.

cd sims/verilator
make CONFIG=GCDTLRocketConfig BINARY=../../tests/gcd.riscv run-binary"

Thanks !

**Comment by SihaoLiu** [comment]
Just want to confirm, your question is
> What is the command "make" in detail ?

If so, [make](https://www.computerhope.com/unix/umake.htm) is a utility for building and maintaining groups of programs (and other types of files) from source code.
