### ISSUE TITLE
Verdi (FSDB) support for ChipYard?

### ISSUE THREAD

**Issue by SihaoLiu** [ucb-bar/chipyard#1070]
**Impact**: software

**Description**

I learned from Synopsys that VCS DVE is about to be deprecated (End of Life) and I was told by them to switch to Verdi. I think Verdi can only use FSDB as waveform format. So I am just wondering if ChipYard team has any plan to support it? Or have you already use Verdi internally?

If you have not supported internally. I am going to open an PR for it since I have partially done that on my side.

**What is a motivating example for changing the behavior?**
VCS DVE is reaching its EOL per Synopsys, Verdi (FSDB) is preferred.

**Comment by jerryz123** [comment]
Yep, we'd be happy to review and accept a PR with this feature
