### ISSUE TITLE
Java Option causing errors

### ISSUE THREAD

**Issue by mehnadnerd** [ucb-bar/chipyard#1079]
The java option MaxPermSize is causing errors on my java environment:
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Homebrew (build 17.0.1+1)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.1+1, mixed mode, sharing)

Unrecognized VM option 'MaxPermSize=256M'
Given that it has been removed since Java 8, we should just remove this flag.

**Comment by tymcauley** [comment]
This was resolved by #1080/#1082, right?

**Comment by jerryz123** [comment]
This has been resolved.
