### ISSUE TITLE
curl -sL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823' gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by Elena32061** [ucb-bar/chipyard#1087]
**Impact**: rtl | software | unknown | other

**Tell us about your environment:**
*Chipyard Version:* 
*OS:* 
*Other:* 

**What is the current behavior?**

**What is the expected behavior?**

**Other information**

Hello, I got this error when I installed the dependencies of the chipard environment on ubuntu20.04 and ubuntu 18.04. I tried to continue, but there will be other errors in the make phase later. Have you encountered any friends, I need your help very much, thank you

Error message:
+ curl -sL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823'
gpg: no valid OpenPGP data found.

**Comment by jerryz123** [comment]
The new conda-based setup flow should avoid these issues. Closing
