### ISSUE TITLE
FPGA Linux Boot Gets Stuck When Using Medium BOOM

### ISSUE THREAD

**Issue by zslwyuan** [ucb-bar/chipyard#1098]
**Impact**: rtl 

**Tell us about your environment:**
*Chipyard Version:* 1.2.0, Hash: 2c0928
*OS:* CentOS 7.4
*Other:* Followed the steps in FPGA prototyping for VCU118

**What is the current behavior?**
We changed the default 1-wide BOOM settings(boot successfully) into 2-wide BOOM (i.e. MediumBoomConfig) with 3 cores.  Then the Linux boot procedure got stuck after "Starting mdev....ok" or got stuck after boot when we started a multi-thread application.

**Comment by Yuxin-Yu** [comment]
Hi bro,I met the same problem when I boot linux with MegaBoom,how do you solve this? @zslwyuan

**Comment by Yuxin-Yu** [comment]
Hello, I have encountered the same problem in GigaBoom and MegaBoom, but occasionally restarting can solve it. How did you solve it @zslwyuan
