### ISSUE TITLE
Link to BOOM paper in README is broken

### ISSUE THREAD

**Issue by christian-lanius** [ucb-bar/chipyard#1099]
Dear All,
Thanks for making this project available online. While looking into the background papers, I received an error 404 when accessing the BOOM paper at https://www.hotchips.org/hc30/1conf/1.03_Berkeley_BROOM_HC30.Berkeley.Celio.v02.pdf

I assume that the correct link would be: https://people.eecs.berkeley.edu/~krste/papers/BROOM-IEEEMicro2019.pdf though this is not the official hotchips website.

Kind regards
Christian

**Comment by abejgonzalez** [comment]
Good catch. I'll update the link. It will be fixed when we next release (in a few days).
