### ISSUE TITLE
TestDriver needs to support longer destination paths to waveforms.

### ISSUE THREAD

**Issue by jerryz123** [ucb-bar/chipyard#113]
Since the longnames are incorporated into the path to simulation output now, this causes some runs to fail.

Should be fixed with https://github.com/freechipsproject/rocket-chip/pull/1988

**Comment by abejgonzalez** [comment]
This is now supported in RC. So in the next bump we can fix this issue.

**Comment by jerryz123** [comment]
Can you open a fake PR with a rocketchip bump to latest? 
This might be good development practice for keeping track of when something breaks with latest rocketchip
