### ISSUE TITLE
run "make CONFIG=SmallBoomConfig" in "/chipyard/sims/verilator"

### ISSUE THREAD

**Issue by hhd166** [ucb-bar/chipyard#1166]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: a6a6a6

### OS Setup

Ex: Output of `uname -a` and `lsb_release -a`

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

When I run "make CONFIG=SmallBoomConfig" in "/chipyard/sims/verilator"
I meet errors as follow:
[error] Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/hanhaodong/Desktop/chipyard/chipyard/.java_tmp
[error] Nonzero exit code returned from runner: 137
[error] (Compile / runMain) Nonzero exit code returned from runner: 137
[error] Total time: 117 s (01:57), completed May 4, 2022, 6:28:43 AM
/home/hanhaodong/Desktop/chipyard/chipyard/common.mk:137: recipe for target 'firrtl_temp' failed
make: *** [firrtl_temp] Error 1

### Expected Behavior

make CONFIG=SmallBoomConfig success

**Comment by 786674917** [comment]
Hello, I also meet this problem, Can you tell me how you fix it?

**Comment by chenc6** [comment]
@786674917 it is probably because of the version of java tools. I got a similar printout but the compilation finished fine on my side. 
![image](https://user-images.githubusercontent.com/79608200/173162682-ade85f68-674d-4b60-8827-67400d9dc870.png)

**Comment by jerryz123** [comment]
Sorry. That error message is not a real error. Ignore it and compilation should continue
