### ISSUE TITLE
Explore Use CIRCT FIRRTL Compiler

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/chipyard#1189]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

Supposedly this works in RC and would give a ~10x boost to FIRRTL runtimes.

### Motivating Example

N/A

**Comment by jerryz123** [comment]
This is done now
