### ISSUE TITLE
Support for Virtex VC707

### ISSUE THREAD

**Issue by mbelda** [ucb-bar/chipyard#1195]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

I would need support for the Xilinx VC707 board.
I have seen that the support for the shell is already done (or started at least).
https://github.com/sifive/fpga-shells/blob/master/src/main/scala/shell/xilinx/VC707Shell.scala

So it just needs to be added to chipyard/fpga/src/main

### Motivating Example

I could use the board to deploy a 16-by-16 Gemmini that does not fit in the artys that had support (and I don't have the vcu118..)

**Comment by gnodipac886** [comment]
Hi there @mbelda did you ever happen to get Gemmini to run on VC707? Cheers

**Comment by mbelda** [comment]
Nop

**Comment by gnodipac886** [comment]
Bump, this will be nice to have. I also want to deploy Gemmini :)

**Comment by Lorilandly** [comment]
I'm trying to get rocket/hwacha working on VC707. Will report back if there's progress.

**Comment by gnodipac886** [comment]
@Lorilandly @mbelda 
I found a working repo here :)
It has Gemmini support too!
https://github.com/eugene-tarassov/vivado-risc-v

**Comment by Lorilandly** [comment]
I'm very exited to announce that my vc707 board has successfully booted.
