### ISSUE TITLE
VCS FATAL ERROR  For simulation in VLSI flow: simulation failed on some test cases

### ISSUE THREAD

**Issue by lesliepy99** [ucb-bar/chipyard#1198]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.7.1

### OS Setup

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

### Other Setup

gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

### Current Behavior

After synthesis and par of TinyRocketConfig, I try to run post-simulation on the test-cases under the directory `$RISCV/riscv64-unknown-elf/share/riscv-tests/benchmarks` by the command ` make sim-par-debug CONFIG=TinyRocketConfig BINARY=$RISCV/riscv64-unknown-elf/share/riscv-tests/benchmarks/qsort.risc`, however, I got the following error:
```
[sim] Running sub-step 'run_simulation'
Executing subprocess: /research/d4/spc/ypu9/chipyard-macro-placement/vlsi/build/chipyard.TestHarness.TinyRocketConfig-ChipTop/sim-par-rundir/simv +permissive +dramsim +dramsim_ini_dir=/research/d4/spc/ypu9/chipyard-macro-placement/generators/testchipip/src/main/resources/dramsim2_ini +max-cycles=10000000 -ucli -do /research/d4/spc/ypu9/chipyard-macro-placement/vlsi/build/chipyard.TestHarness.TinyRocketConfig-ChipTop/sim-par-rundir/run.tcl +permissive-off /research/d4/spc/ypu9/chipyard-macro-placement/riscv-tools-install/riscv64-unknown-elf/share/riscv-tests/benchmarks/qsort.riscv
Notice: timing checks disabled with +notimingcheck at compile-time
Chronologic VCS simulator copyright 1991-2017
Contains Synopsys proprietary information.
Compiler version M-2017.03-SP1_Full64; Runtime version M-2017.03-SP1_Full64;  Jul 14 22:12 2022
ucli% source /research/d4/spc/ypu9/chipyard-macro-placement/vlsi/build/chipyard.TestHarness.TinyRocketConfig-ChipTop/sim-par-rundir/force_regs.ucli
ucli% run
[UART] UART0 is here (stdin/stdout).
Fatal: "/research/d4/spc/ypu9/chipyard-macro-placement/vlsi/generated-src/chipyard.TestHarness.TinyRocketConfig/chipyard.TestHarness.TinyRocketConfig.harness.v", 25587: TestDriver.testHarness.ram.buffer_1.monitor: at time 109190500000 fs
$finish called from file "/research/d4/spc/ypu9/chipyard-macro-placement/vlsi/generated-src/chipyard.TestHarness.TinyRocketConfig/chipyard.TestHarness.TinyRocketConfig.harness.v", line 25587.
$finish at simulation time           1091905000
           V C S   S i m u l a t i o n   R e p o r t
Time: 109190500000 fs
CPU Time:     49.710 seconds;       Data structure size:  41.7Mb
Thu Jul 14 22:12:55 2022
Action sim config output written to output.json
```
Seems that the simulation failed.

### Expected Behavior

The simulation should pass.

**Comment by jerryz123** [comment]
You are trying to run a RV64 binary on a RV32 core
