### ISSUE TITLE
Compiling and Running C++ Code

### ISSUE THREAD

**Issue by fakoberer** [ucb-bar/chipyard#1207]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

Running a c++ code on either Verilator or Spike

### Motivating Example

I want to compile and run a very simple c++ code on the platforms that I mentioned above. However, I was not able to find any stuff related to that. If there is anyone has knowledge about it, will he/she please share it ?

Thanks in advance.

**Comment by jerryz123** [comment]
Start with spike's README
