### ISSUE TITLE
Failed in RTL simulation on hwacha using verilator

### ISSUE THREAD

**Issue by YiKangOY** [ucb-bar/chipyard#1220]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.7.1
Hash: 9926642

### OS Setup

Ex: Output of `uname -a` and `lsb_release -a`

Linux ca9ac4e7af1a 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

I have configured environment as the documentation says. I ran `make SUB_PROJECT=hwacha` in `sims/verilator`

The log has been attached in the "Other information"

### Expected Behavior

The make should worked.

### Other Information

[hwacha.log](https://github.com/ucb-bar/chipyard/files/9544353/hwacha.log)

**Comment by jerryz123** [comment]
`HwachaConfig` is not supported. Use `HwachaRocketConfig`.

https://github.com/ucb-bar/chipyard/blob/03083507d3c47ffb943bb4162f7b992082f84363/generators/chipyard/src/main/scala/config/RocketConfigs.scala#L31
