### ISSUE TITLE
bug:change hwacha config

### ISSUE THREAD

**Issue by zzmsir** [ucb-bar/chipyard#1234]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.7.1
Hash: 992664220d95edf610475031fd8a82d0cd743f7f

### OS Setup

dont care

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

CONFIG=HwachaRocketConfig
change DefaultHwachaConfig
case HwachaNBanks => 4  >> case HwachaNBanks => 8
case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 16) >> case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 32)
Current Behavior:hwacha cannot load complete valid data 
sometimes meeting needed data, valid single cannot pull up(set 1)
![image](https://user-images.githubusercontent.com/91862179/193225237-e969dbc7-1b4f-4d68-adbd-3bacabf2f151.png)

### Expected Behavior

CONFIG=HwachaRocketConfig
change DefaultHwachaConfig
case HwachaNBanks => 4  >> case HwachaNBanks => 8
case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 16) >> case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 32)
Expected Behavior:hwacha can load complete valid data 
alltime meeting needed data, valid single must pull up(set 1)
![1664526289(1)](https://user-images.githubusercontent.com/91862179/193226600-f87d9c1c-17f0-49a6-a63f-2d51266899a7.png)

### Other Information

CONFIG=HwachaRocketConfig
change DefaultHwachaConfig
case HwachaNBanks => 4  >> case HwachaNBanks => 8
case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 16) >> case SystemBusKey => up(SystemBusKey, site).copy(beatBytes = 32)

**Comment by jerryz123** [comment]
The TL-A channel is a decoupled interface. Most likely on those cycles, the VMU intentionally desserts valid.

Are you seeing an erroring test case that can be traced back to this behavior?
