### ISSUE TITLE
What functions is UpdateBrMask in Dcache of Boom?

### ISSUE THREAD

**Issue by napian-yun** [ucb-bar/chipyard#1243]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

io.lsu.resp(w).bits  := UpdateBrMask(io.lsu.brupdate, resp(w).bits)
object UpdateBrMask
{
  def apply(brupdate: BrUpdateInfo, uop: MicroOp): MicroOp = {
    val out = WireInit(uop)
    out.br_mask := GetNewBrMask(brupdate, uop)
    out
  }
  def apply[T <: boom.common.HasBoomUOP](brupdate: BrUpdateInfo, bundle: T): T = {
    val out = WireInit(bundle)
    out.uop.br_mask := GetNewBrMask(brupdate, bundle.uop.br_mask)
    out
  }
  def apply[T <: boom.common.HasBoomUOP](brupdate: BrUpdateInfo, bundle: Valid[T]): Valid[T] = {
    val out = WireInit(bundle)
    out.bits.uop.br_mask := GetNewBrMask(brupdate, bundle.bits.uop.br_mask)
    out.valid := bundle.valid && !IsKilledByBranch(brupdate, bundle.bits.uop.br_mask)
    out
  }
}
----------------------------------
What functions is UpdateBrMask in Dcache of Boom?

### Motivating Example

What functions is UpdateBrMask in Dcache of Boom?

**Comment by jerryz123** [comment]
This question is better suited for the boom repository.

The UpdateBrMask function is used to propagate branch resolution information to inflight instructions. As branch slots can get reused after the branch is resolved, all instructions in a branch shadow must clear the dependency bit on that branch.
