### ISSUE TITLE
Build ESP Tools fail on ARM64 Linux 

### ISSUE THREAD

**Issue by willliu** [ucb-bar/chipyard#1267]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: -----

Follow Gemmini tutorial:

git checkout 117624d8eea27bafd613eec09e9b9b3e31239e08

### OS Setup

`uname -a`
Linux ubuntu-linux-22-04-desktop 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:04:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

`lsb_release -a`
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

`conda list`
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py310h761cc84_1005    conda-forge
bzip2                     1.0.8                hf897c2e_4    conda-forge
ca-certificates           2022.9.24            h4fd8a4c_0    conda-forge
cachecontrol              0.12.12            pyhd8ed1ab_1    conda-forge
cachy                     0.3.0              pyhd8ed1ab_1    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310hf0c4615_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
click-default-group       1.2.2              pyhd8ed1ab_1    conda-forge
clikit                    0.6.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0          py310h4c7bcd0_1    conda-forge
conda-lock                1.2.1              pyhd8ed1ab_1    conda-forge
conda-package-handling    1.9.0           py310h761cc84_1    conda-forge
crashtest                 0.3.1              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2          py310h674ca28_2    conda-forge
dbus                      1.13.6               h12b9eeb_3    conda-forge
distlib                   0.3.5              pyhd8ed1ab_0    conda-forge
ensureconda               1.4.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                ha18d298_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               ha18d298_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
keyring                   23.9.3          py310h4c7bcd0_1    conda-forge
ld_impl_linux-aarch64     2.39                 ha75b1e8_0    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc-ng                 12.2.0              h607ecd0_19    conda-forge
libglib                   2.74.1               h58953e2_0    conda-forge
libgomp                   12.2.0              h607ecd0_19    conda-forge
libiconv                  1.17                 h9cdd2b7_0    conda-forge
libnsl                    2.0.0                hf897c2e_0    conda-forge
libsqlite                 3.39.4               hf9034f9_0    conda-forge
libstdcxx-ng              12.2.0              hc13a102_19    conda-forge
libuuid                   2.32.1            hf897c2e_1000    conda-forge
libzlib                   1.2.13               h4e544f5_4    conda-forge
markupsafe                2.1.1           py310hdc54845_2    conda-forge
more-itertools            9.0.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4           py310h9ceb0a0_1    conda-forge
ncurses                   6.3                  headf329_1    conda-forge
openssl                   3.0.7                h4e544f5_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.37                he7b27c6_1    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
pycosat                   0.6.4           py310h761cc84_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.2          py310h761cc84_1    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h92ab765_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyyaml                    6.0             py310h761cc84_5    conda-forge
readline                  8.1.2                h38e3740_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.17.21         py310h761cc84_2    conda-forge
ruamel.yaml.clib          0.2.7           py310h761cc84_0    conda-forge
ruamel_yaml               0.15.80         py310h761cc84_1008    conda-forge
secretstorage             3.3.3           py310hbbe02a8_1    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               hd8af866_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
virtualenv                20.16.5         py310hbbe02a8_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h9cdd2b7_0    conda-forge
yaml                      0.2.5                hf897c2e_2    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge

### Other Setup

Follow https://github.com/ucb-bar/gemmini

git clone https://github.com/ucb-bar/chipyard.git
cd chipyard
git checkout 117624d8eea27bafd613eec09e9b9b3e31239e08
./scripts/init-submodules-no-riscv-tools.sh
./scripts/build-toolchains.sh esp-tools

### Current Behavior

Build ESP tools failed. Error 127.

chipyard$ ./scripts/build-toolchains.sh esp-tools
Installing toolchain to /home/parallels/Git/chipyard/esp-tools-install
=>  Starting riscv-gnu-toolchain build
==>  Initializing riscv-gnu-toolchain submodule
Skipping submodule '../toolchains/esp-tools/riscv-gnu-toolchain/'
Cloning into '/home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/riscv-glibc'...
Cloning into '/home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/riscv-newlib'...
Submodule path 'toolchains/esp-tools/riscv-gnu-toolchain/riscv-gcc': checked out 'b6cdb9a9f5eb1c4ae5b7769d90a79f29853a0fe2'
Submodule path 'toolchains/esp-tools/riscv-gnu-toolchain/riscv-glibc': checked out '06983fe52cfe8e4779035c27e8cc5d2caab31531'
Submodule path 'toolchains/esp-tools/riscv-gnu-toolchain/riscv-newlib': checked out '0d24a86822a5ee73d6a6aa69e2a0118aa1e35204'
==>  Configuring riscv-gnu-toolchain
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for fgrep... /usr/bin/grep -F
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for bash... /bin/bash
checking for __gmpz_init in -lgmp... yes
checking for mpfr_init in -lmpfr... yes
checking for mpc_init2 in -lmpc... yes
checking for curl... /usr/bin/curl
checking for wget... /usr/bin/wget
checking for ftp... /usr/bin/ftp
configure: creating ./config.status
config.status: creating Makefile
config.status: creating scripts/wrapper/awk/awk
config.status: creating scripts/wrapper/sed/sed
==>  Building riscv-gnu-toolchain
rm -rf stamps/build-binutils-newlib build-binutils-newlib
mkdir build-binutils-newlib
rm -rf stamps/build-gdb-newlib build-gdb-newlib
mkdir build-gdb-newlib
cd build-gdb-newlib && CC_FOR_TARGET=riscv64-unknown-elf-gcc /home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/build/../riscv-gdb/configure \
	--target=riscv64-unknown-elf \
	 \
	--prefix=/home/parallels/Git/chipyard/esp-tools-install \
	 \
	--disable-werror \
	--with-expat=yes  \
	--enable-gdb \
	--disable-gas \
	--disable-binutils \
	--disable-ld \
	--disable-gold \
	--disable-gprof
/bin/sh: 1: /home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/build/../riscv-gdb/configure: not found
gmake: *** [Makefile:388: stamps/build-gdb-newlib] Error 127
gmake: *** Waiting for unfinished jobs....
cd build-binutils-newlib && CC_FOR_TARGET=riscv64-unknown-elf-gcc /home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/build/../riscv-binutils/configure \
	--target=riscv64-unknown-elf \
	 \
	--prefix=/home/parallels/Git/chipyard/esp-tools-install \
	 \
	--disable-werror \
	--with-expat=yes  \
	--disable-gdb \
	--disable-sim \
	--disable-libdecnumber \
	--disable-readline
/bin/sh: 1: /home/parallels/Git/chipyard/toolchains/esp-tools/riscv-gnu-toolchain/build/../riscv-binutils/configure: not found
gmake: *** [Makefile:369: stamps/build-binutils-newlib] Error 127

### Expected Behavior

Should build successful.

**Comment by jerryz123** [comment]
We'll stop maintaining esp-tools soon. Esp-tools is not longer required for the latest versions of gemmini

**Comment by willliu** [comment]
👍
