### ISSUE TITLE
Complex L2 config for CI

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/chipyard#131]
Can we also add a config that sets parameters in the L2 config?
`Rocket4BankL2` or `Rocket1MBL2` and just have them build in CI?
I think its important to test the number of banks and the number of memory channels. Having both of those parameters set has caused problems in the past and I think was the reason for Howie's rocket-chip PR.

_Originally posted by @colinschmidt in https://github.com/ucb-bar/chipyard/pull/128/files_

**Comment by jerryz123** [comment]
This is done
