### ISSUE TITLE
VCU118, Linux is not booting

### ISSUE THREAD

**Issue by athakore-personal** [ucb-bar/chipyard#1320]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: Stable
Hash: a6a6a6

### OS Setup

We use "gdisk" on MacOS to partition the sd-card following the same steps as given in the documentation. The error we recieve seems like there is an issue with Linux booting/ linux image 

### Other Setup

We followed the steps given in the stable version of documentation here :
https://chipyard.readthedocs.io/en/stable/Prototyping/VCU118.html

We searched different tickets, one potential problem could that we built MegaBoomcore, but changing it to LargeBoomCore also didn't help. 

We also went through the issue here, but our problems aren't the same:
https://github.com/ucb-bar/chipyard/issues/957

Our gdisk partitions the sd-card as given in instructions and we have all types of file system avaialible as well. 

The only difference is the mkfs command used to prototype data in second partition. sudo newfs_hfs -v "PrototypeData" /dev/disk4s2 

### Current Behavior

Currently, we recieve the following error : 
sd_card : timeout
error

<photo>
<img width="129" alt="Screenshot 2023-02-01 at 2 30 08 PM" src="https://user-images.githubusercontent.com/89951612/216147882-cac74bd0-4dc1-4771-a856-d6d720500a59.png">

### Expected Behavior

The risc-v linux should be booted onto the boom core, but it isn't.

**Comment by michael-etzkorn** [comment]
I don't think you're getting past SD card initialization. The format of the
image or what image you load doesn't even matter here.

To confirm some things:

   - Are you using a PMOD to SPI connector? Chipyard's VCU118 build uses an
   SD card over the female PMOD pins. The built-in SD card slot is for the
   board's Zynq controller.
   - Have you tested another SD card? Sometimes, it's an SD card issue.
