### ISSUE TITLE
Remove Commit on Master Check

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/chipyard#135]
While in theory, commit on master check seems like a good idea I think it needs to be revisited. Do we want this check here to error? Or do we want it to be a warning instead? In the current case, `testchipip` needs to have its PR's merged for things to work. So in the meantime, the `testchipip` commit does not point to master. I think that this case will probably be more frequent so not erroring would be better. Thoughts?

**Comment by jerryz123** [comment]
I disagree. It's a reminder that testchipip needs to be looked at

**Comment by jerryz123** [comment]
Resolved by #184
