### ISSUE TITLE
run-binary-debug is confusing

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/chipyard#146]
It's not clear that you need to set the BINARY variable. I'd recommend changing it to a pattern rule (e.g. `run-debug-%`). It's also not set as a `.PHONY` target, which is wrong. I'll PR this change next week.

**Comment by jerryz123** [comment]
Will the pattern rule method work when the binary is not in the same directory?

**Comment by jwright6323** [comment]
We can make something work

**Comment by colinschmidt** [comment]
I think we want to take the approach of doing the simple things being easy and doing the hard things possible.
Running the tests bundled with chipyard that are in the right directory should be easy.
Running an executable located in some far away directory should be possible.

**Comment by jerryz123** [comment]
I just do `make run-binary-debug BINARY=output/(longname)/(testname)`
Perhaps a `run-test-%` rule in addition to the `run-binary` rule would work?

**Comment by jwright6323** [comment]
This is probably no longer needed
