### ISSUE TITLE
"conda-lock not found" during "build-setup.sh riscv-tools" on ubuntu22.04 

### ISSUE THREAD

**Issue by kumarvemuri** [ucb-bar/chipyard#1648]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.10.0
Hash: a6a6a6

### OS Setup

Ex: Output of `uname -a` + `lsb_release -a` + `printenv` + `conda

Linux Le1w-gpu-a4000 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
NX_TEMP=/tmp
SHELL=/bin/bash
SESSION_MANAGER=local/Le1w-gpu-a4000:@/tmp/.ICE-unix/82832,unix/Le1w-gpu-a4000:/tmp/.ICE-unix/82832
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-xorg:/etc/xdg
NX_SESSION_ID=96FFE76CB4703A72667503C2DFE83231
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
CONDA_EXE=/home/kvemuri/anaconda3/bin/conda
NX_CUPS_BIN=/usr/bin
_CE_M=
PULSE_RUNTIME_PATH=/run/user/10725/pulse
LANGUAGE=en_GB:en
GNOME_SHELL_SESSION_MODE=ubuntu
SSH_AUTH_SOCK=/run/user/10725/keyring/ssh
NX_ROOT=/home/kvemuri/.nx
XMODIFIERS=@im=ibus
DESKTOP_SESSION=ubuntu-xorg
KRB5CCNAME=FILE:/tmp/tktTUdr7G
PWD=/home/kvemuri/chipyard
LOGNAME=kvemuri
XDG_SESSION_TYPE=x11
CONDA_PREFIX=/home/kvemuri/anaconda3
XAUTHORITY=/home/kvemuri/.Xauthority
PULSE_SCRIPT=/home/kvemuri/.nx/nxdevice/D-1003-96FFE76CB4703A72667503C2DFE83231/audio/default.pa
HOME=/home/kvemuri
USERNAME=kvemuri
LANG=en_GB.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6800
CONDA_PROMPT_MODIFIER=(base) 
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/ba33cac6_4e39_4807_a780_72bc64423fc1
PULSE_CLIENTCONFIG=/home/kvemuri/.nx/nxdevice/D-1003-96FFE76CB4703A72667503C2DFE83231/audio/client.conf
NX_CONNECTION=10.60.40.5 50103 10.60.20.35 4000
NX_RUNNER=/usr/NX/bin/nxrunner
NX_SYSTEM=/usr/NX
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
_CE_CONDA=
LESSOPEN=| /usr/bin/lesspipe %s
LIBVIRT_DEFAULT_URI=qemu:///system
USER=kvemuri
GNOME_TERMINAL_SERVICE=:1.85
CONDA_SHLVL=1
DISPLAY=:1003
SHLVL=1
QT_IM_MODULE=ibus
XDG_SESSION_ID=c15
DBUS_STARTER_ADDRESS=unix:abstract=/tmp/dbus-X0OIXmkeMU,guid=6d50ac7654d9727ba8fc9d3e6544c454
CONDA_PYTHON_EXE=/home/kvemuri/anaconda3/bin/python
LD_LIBRARY_PATH=usr/local/cuda-12.2/lib64
XDG_RUNTIME_DIR=/run/user/10725
CONDA_DEFAULT_ENV=base
PULSE_CONFIG=/home/kvemuri/.nx/nxdevice/D-1003-96FFE76CB4703A72667503C2DFE83231/audio/daemon.conf
XDG_DATA_DIRS=/usr/share/ubuntu-xorg:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
GDK_BACKEND=x11
PATH=/home/kvemuri/anaconda3/bin:/home/kvemuri/anaconda3/condabin:/home/kvemuri/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kvemuri/.local/bin:/usr/local/cuda-12.2/bin
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-X0OIXmkeMU,guid=6d50ac7654d9727ba8fc9d3e6544c454
MAIL=/var/mail/kvemuri
PULSE_SERVER=/home/kvemuri/.nx/nxdevice/D-1003-96FFE76CB4703A72667503C2DFE83231/audio/native.socket
NXDIR=/usr/NX
_=/usr/bin/printenv
OLDPWD=/home/kvemuri/anaconda3/bin
# packages in environment at /home/kvemuri/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39h06a4308_1  
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
aiohttp                   3.8.1            py39h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.05                  py39_0  
anaconda-client           1.9.0            py39h06a4308_0  
anaconda-navigator        2.1.4            py39h06a4308_0  
anaconda-project          0.10.2             pyhd3eb1b0_0  
anyio                     3.5.0            py39h06a4308_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.6.6            py39h06a4308_0  
astropy                   5.0.4            py39hce1f21e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
automat                   20.2.0                     py_0  
autopep8                  1.6.0              pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.2.0            py39he8ac12f_0  
beautifulsoup4            4.11.1           py39h06a4308_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
bitarray                  2.4.1            py39h7f8727e_0  
bkcharts                  0.2              py39h06a4308_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.0               h8c45485_0  
bokeh                     2.4.2            py39h06a4308_0  
boto3                     1.21.32            pyhd3eb1b0_0  
botocore                  1.24.32            pyhd3eb1b0_0  
bottleneck                1.3.4            py39hce1f21e_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
brunsli                   0.1                  h2531618_0  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.3.29            h06a4308_1  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.10.8        py39h06a4308_2  
cffi                      1.15.0           py39hd667e15_1  
cfitsio                   3.470                hf0d0db6_6  
chardet                   4.0.0           py39h06a4308_1003  
charls                    2.2.0                h2531618_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py39h06a4308_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
clyent                    1.2.2            py39h06a4308_1  
colorama                  0.4.4              pyhd3eb1b0_0  
colorcet                  2.0.6              pyhd3eb1b0_0  
conda                     4.12.0           py39h06a4308_0  
conda-build               3.21.8           py39h06a4308_2  
conda-content-trust       0.1.1              pyhd3eb1b0_0  
conda-env                 2.6.0                         1  
conda-pack                0.6.0              pyhd3eb1b0_0  
conda-package-handling    1.8.1            py39h7f8727e_0  
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-token               0.3.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
constantly                15.1.0             pyh2b92418_0  
cookiecutter              1.7.3              pyhd3eb1b0_0  
cryptography              3.4.8            py39hd23ed53_0  
cssselect                 1.1.0              pyhd3eb1b0_0  
curl                      7.82.0               h7f8727e_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.28          py39h295c915_0  
cytoolz                   0.11.0           py39h27cfd23_0  
daal4py                   2021.5.0         py39h78b71dc_0  
dal                       2021.5.1           h06a4308_803  
dask                      2022.2.1           pyhd3eb1b0_0  
dask-core                 2022.2.1           pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
datashader                0.13.0             pyhd3eb1b0_1  
datashape                 0.5.4            py39h06a4308_1  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
distributed               2022.2.1           pyhd3eb1b0_0  
docutils                  0.17.1           py39h06a4308_1  
entrypoints               0.4              py39h06a4308_0  
et_xmlfile                1.1.0            py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.4                h295c915_0  
filelock                  3.6.0              pyhd3eb1b0_0  
flake8                    3.9.2              pyhd3eb1b0_0  
flask                     1.1.2              pyhd3eb1b0_0  
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
frozenlist                1.2.0            py39h7f8727e_0  
fsspec                    2022.2.0           pyhd3eb1b0_0  
future                    0.18.2           py39h06a4308_1  
gensim                    4.1.2            py39h295c915_0  
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
glob2                     0.7                pyhd3eb1b0_0  
gmp                       6.2.1                h2531618_2  
gmpy2                     2.1.2            py39heeb90bb_0  
google-api-core           1.25.1             pyhd3eb1b0_0  
google-auth               1.33.0             pyhd3eb1b0_0  
google-cloud-core         1.7.1              pyhd3eb1b0_0  
google-cloud-storage      1.31.0                     py_0  
google-crc32c             1.1.2            py39h27cfd23_0  
google-resumable-media    1.3.1              pyhd3eb1b0_1  
googleapis-common-protos  1.53.0           py39h06a4308_0  
greenlet                  1.1.1            py39h295c915_0  
grpcio                    1.42.0           py39hce63b2e_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      3.6.0            py39ha0f2276_0  
hdf5                      1.10.6               hb1b8bf9_0  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.14.8             pyhd3eb1b0_0  
hvplot                    0.7.3              pyhd3eb1b0_1  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
imagecodecs               2021.8.26        py39h4cda21f_0  
imageio                   2.9.0              pyhd3eb1b0_0  
imagesize                 1.3.0              pyhd3eb1b0_0  
importlib-metadata        4.11.3           py39h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
incremental               21.3.0             pyhd3eb1b0_0  
inflection                0.5.1            py39h06a4308_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.6.5              pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.9.1            py39h06a4308_0  
ipython                   8.2.0            py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.0.4              pyhd3eb1b0_1  
itsdangerous              2.0.1              pyhd3eb1b0_0  
jdcal                     1.4.1              pyhd3eb1b0_0  
jedi                      0.18.1           py39h06a4308_1  
jeepney                   0.7.1              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_3  
jmespath                  0.10.0             pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h7f8727e_0  
jq                        1.6               h27cfd23_1000  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.4.0            py39h06a4308_0  
jupyter                   1.0.0            py39h06a4308_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.9.2            py39h06a4308_0  
jupyter_server            1.13.5             pyhd3eb1b0_0  
jupyterlab                3.3.2              pyhd3eb1b0_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  h7b6447c_2  
keyring                   23.4.0           py39h06a4308_0  
kiwisolver                1.3.2            py39h295c915_0  
krb5                      1.19.2               hac12032_0  
lazy-object-proxy         1.6.0            py39h27cfd23_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      3.0                  h295c915_0  
libaec                    1.0.4                he6710b0_1  
libarchive                3.4.2                h62408e4_0  
libcrc32c                 1.1.1                he6710b0_2  
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libidn2                   2.3.2                h7f8727e_0  
liblief                   0.11.5               h295c915_1  
libllvm11                 11.1.0               h3826bc1_1  
libnghttp2                1.46.0               hce63b2e_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.19.1               h4ff587b_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
libxslt                   1.1.34               hc22bd24_0  
libzopfli                 1.0.3                he6710b0_0  
llvmlite                  0.38.0           py39h4ff587b_0  
locket                    0.2.1            py39h06a4308_2  
lxml                      4.8.0            py39h1f438cf_0  
lz4-c                     1.9.3                h295c915_1  
lzo                       2.10                 h7b6447c_2  
markdown                  3.3.4            py39h06a4308_0  
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.5.1            py39h06a4308_1  
matplotlib-base           3.5.1            py39ha18d171_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.6.1            py39h06a4308_1  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mock                      4.0.3              pyhd3eb1b0_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpi                       1.0                       mpich  
mpich                     3.3.2                hc856adb_0  
mpmath                    1.2.1            py39h06a4308_0  
msgpack-python            1.0.2            py39hff7bd54_1  
multidict                 5.2.0            py39h7f8727e_2  
multipledispatch          0.6.0            py39h06a4308_0  
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3            py39h06a4308_1  
navigator-updater         0.2.1                    py39_1  
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py39h06a4308_0  
nbconvert                 6.4.4            py39h06a4308_0  
nbformat                  5.3.0            py39h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5            py39h06a4308_0  
networkx                  2.7.1              pyhd3eb1b0_0  
nltk                      3.7                pyhd3eb1b0_0  
nose                      1.3.7           pyhd3eb1b0_1008  
notebook                  6.4.8            py39h06a4308_0  
numba                     0.55.1           py39h51133e4_0  
numexpr                   2.8.1            py39h6abb31d_0  
numpy                     1.21.5           py39he7a7128_1  
numpy-base                1.21.5           py39hf524024_1  
numpydoc                  1.2                pyhd3eb1b0_0  
olefile                   0.46               pyhd3eb1b0_0  
oniguruma                 6.9.7.1              h27cfd23_0  
openjpeg                  2.4.0                h3ad879b_0  
openpyxl                  3.0.9              pyhd3eb1b0_0  
openssl                   1.1.1n               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.2            py39h295c915_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     0.13.0           py39h06a4308_0  
param                     1.12.0             pyhd3eb1b0_0  
parsel                    1.6.0            py39h06a4308_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
patchelf                  0.13                 h295c915_0  
pathspec                  0.7.0                      py_0  
patsy                     0.5.2            py39h06a4308_1  
pcre                      8.45                 h295c915_0  
pep8                      1.7.1            py39h06a4308_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
pkginfo                   1.8.2              pyhd3eb1b0_0  
plotly                    5.6.0              pyhd3eb1b0_0  
pluggy                    1.0.0            py39h06a4308_1  
poyo                      0.5.0              pyhd3eb1b0_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
protego                   0.1.16                     py_0  
protobuf                  3.19.1           py39h295c915_0  
psutil                    5.8.0            py39h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py                        1.11.0             pyhd3eb1b0_0  
py-lief                   0.11.5           py39h295c915_1  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycodestyle               2.7.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py39h27cfd23_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.4.6            py39h06a4308_0  
pycurl                    7.44.1           py39h8f2d780_1  
pydispatcher              2.0.5            py39h06a4308_2  
pydocstyle                6.1.1              pyhd3eb1b0_0  
pyerfa                    2.0.0            py39h27cfd23_0  
pyflakes                  2.3.1              pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyhamcrest                2.0.2              pyhd3eb1b0_2  
pyjwt                     2.1.0            py39h06a4308_0  
pylint                    2.9.6            py39h06a4308_1  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyodbc                    4.0.32           py39h295c915_1  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pyrsistent                0.18.0           py39heee7806_0  
pysocks                   1.7.1            py39h06a4308_0  
pytables                  3.6.1            py39h77479fe_1  
pytest                    7.1.1            py39h06a4308_0  
python                    3.9.12               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lsp-black          1.0.0              pyhd3eb1b0_0  
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0  
python-lsp-server         1.2.4              pyhd3eb1b0_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.0            py39h2531618_3  
pytz                      2021.3             pyhd3eb1b0_0  
pyviz_comms               2.0.2              pyhd3eb1b0_0  
pywavelets                1.3.0            py39h7f8727e_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    6.0              py39h7f8727e_1  
pyzmq                     22.3.0           py39h295c915_2  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.3.0              pyhd3eb1b0_0  
qtpy                      2.0.1              pyhd3eb1b0_0  
queuelib                  1.5.0            py39h06a4308_0  
readline                  8.1.2                h7f8727e_1  
regex                     2022.3.15        py39h7f8727e_0  
requests                  2.27.1             pyhd3eb1b0_0  
requests-file             1.5.1              pyhd3eb1b0_0  
ripgrep                   12.1.1                        0  
rope                      0.22.0             pyhd3eb1b0_0  
rsa                       4.7.2              pyhd3eb1b0_1  
rtree                     0.9.7            py39h06a4308_1  
ruamel_yaml               0.15.100         py39h27cfd23_0  
s3transfer                0.5.0              pyhd3eb1b0_0  
scikit-image              0.19.2           py39h51133e4_0  
scikit-learn              1.0.2            py39h51133e4_1  
scikit-learn-intelex      2021.5.0         py39h06a4308_0  
scipy                     1.7.3            py39hc147768_0  
scrapy                    2.6.1            py39h06a4308_0  
seaborn                   0.11.2             pyhd3eb1b0_0  
secretstorage             3.3.1            py39h06a4308_0  
send2trash                1.8.0              pyhd3eb1b0_1  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                61.2.0           py39h06a4308_0  
sip                       4.19.13          py39h295c915_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.1.0              pyhd3eb1b0_0  
snappy                    1.1.9                h295c915_0  
sniffio                   1.2.0            py39h06a4308_1  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    4.4.0              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0  
spyder                    5.1.5            py39h06a4308_1  
spyder-kernels            2.1.3            py39h06a4308_0  
sqlalchemy                1.4.32           py39h7f8727e_0  
sqlite                    3.38.2               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.2           py39h7f8727e_0  
sympy                     1.10.1           py39h06a4308_0  
tabulate                  0.8.9            py39h06a4308_0  
tbb                       2021.5.0             hd09550d_0  
tbb4py                    2021.5.0         py39hd09550d_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.0.1            py39h06a4308_0  
terminado                 0.13.1           py39h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2021.7.2           pyhd3eb1b0_2  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.11               h1ccaba5_0  
tldextract                3.2.0              pyhd3eb1b0_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     1.2.2              pyhd3eb1b0_0  
toolz                     0.11.2             pyhd3eb1b0_0  
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.64.0           py39h06a4308_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
twisted                   22.2.0           py39h7f8727e_0  
typed-ast                 1.4.3            py39h7f8727e_1  
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
ujson                     5.1.0            py39h295c915_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
unixodbc                  2.3.9                h7b6447c_0  
urllib3                   1.26.9           py39h06a4308_0  
w3lib                     1.21.0             pyhd3eb1b0_0  
watchdog                  2.1.6            py39h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
websocket-client          0.58.0           py39h06a4308_4  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wget                      1.21.3               h0b77cf5_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39h06a4308_0  
wrapt                     1.12.1           py39he8ac12f_1  
wurlitzer                 3.0.2            py39h06a4308_0  
xarray                    0.20.1             pyhd3eb1b0_1  
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                3.0.3              pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0             pyhd3eb1b0_0  
yarl                      1.6.3            py39h27cfd23_0  
zeromq                    4.3.4                h2531618_0  
zfp                       0.5.5                h295c915_6  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.12               h7f8727e_2  
zope                      1.0              py39h06a4308_1  
zope.interface            5.4.0            py39h7f8727e_0  
zstd                      1.4.9                haebb681_0  

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

I am exploring chipyard for the first time. Am settng up chipyard on ubuntu 22.04 and have followed the instructions in section 1.4 of the documentation for "initial repository setup". The "./build-setup.sh riscv-tools" command fails with the following : **_"./build-setup.sh: line 126: conda-lock: command not found"_**

Can anyone pl share pointers to get around this issue? Thanks in advance.

### Expected Behavior

the "build-setup.sh riscv-tools" should complete a full installation of chipyard on my system.

**Comment by abejgonzalez** [comment]
You need to install conda-lock into your base conda environment as detailed here: https://chipyard.readthedocs.io/en/stable/Chipyard-Basics/Initial-Repo-Setup.html#default-requirements-installation
