### ISSUE TITLE
How to remove the PTW from Rocket Core.

### ISSUE THREAD

**Issue by ashutgupta28** [ucb-bar/chipyard#1669]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: a6a6a6

### OS Setup

<img width="769" alt="image" src="https://github.com/ucb-bar/chipyard/assets/128355643/b0b51ef7-02a8-405e-b899-da40100e0dc7">

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

Hi.
I don't want PTW in my Rocket SoC because I am not using Virtual Memory. I have tried to remove it class  from the Tile.scala but I am getting the compiler error. 

### Expected Behavior

Can someone help how can I remove it ?

**Comment by jerryz123** [comment]
Disabling `usingVM` will remove all PTW-related hardware. The PTW module will still exist, but it will not contain anything substantial.
