### ISSUE TITLE
Can't get vpd file when running Boom in verilator

### ISSUE THREAD

**Issue by zhangkanqi** [ucb-bar/chipyard#1715]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.10.0
Chipyard Hash: b7644b2455cc4bae190e811a5d8085f3aad85b87
Boom Hash: 1a153d4974977a2d5f8baa9b4de51b3337d230fe

### OS Setup

Linux 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 GNU/Linux
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch

### Current Behavior

I modified Makefile in verilator to:
![image](https://github.com/ucb-bar/chipyard/assets/34207592/57605afb-0d69-4338-9190-c3bb2d750235)

Then I run a binary file with boom-debug using verilator, as shown in the following figure:
![image](https://github.com/ucb-bar/chipyard/assets/34207592/557a0ccf-12a3-413b-a3cf-065c49cb55ae)

However, it doesn't generate vpd file after runing. Do you know why this happened and how to fix this?

### Expected Behavior

Generate vpd file after runing binary file in Boom using verilator.

**Comment by jerryz123** [comment]
Verilator generates VCDs, not VPDs. This is expected behavior. 

If you want to convert to VPD, you can use the Synopsys vcd2vpd tool, if you have that available.
