### ISSUE TITLE
How can we integrate riscv-dv to test boom core? 

### ISSUE THREAD

**Issue by Sai-Manish** [ucb-bar/chipyard#1879]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

I would like to know how can we integrate riscv-dv (https://github.com/chipsalliance/riscv-dv) into chipyard environment to test out boom core, similarly to torture tests?

### Motivating Example

Currently from my observation riscv-dv is coming with new features, would like to test it out on boom core.

**Comment by jerryz123** [comment]
The RTL simulators generated by chipyard can execute any properly compiled baremetal RISC-V binary.  Feel free to try running riscv-dv generated tests on these simulators.
