### ISSUE TITLE
Is the data in the inclusive L2 cache synchronized with the data in the DDR, or how can I enable the write-through function of the L2 cache?

### ISSUE THREAD

**Issue by Yuxin-Yu** [ucb-bar/chipyard#1915]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

no

### Motivating Example

no

**Comment by jerryz123** [comment]
There is no write-through capability currently implemented.

For write-through support, you can write to the MBUS bypass mechanism if you enable it, note that this will be an incoherent write to backing memory.

**Comment by Yuxin-Yu** [comment]
Hi @jerryz123 ,Thanks for your reply. Do you have any plans to add write-through functionality? Also, could you be more specific about the MBUS bypass mechanism you mentioned?

**Comment by jerryz123** [comment]
I don't have plans to add write-through functionality.
Look at `SbusBypassRocketConfig` and `WithExtMemSbusBypass`. These configs add an address alias (OR in a high-bit into your physical address), through which the system will bypass the L2 and incoherently access DRAM.

**Comment by Yuxin-Yu** [comment]
Thank you @jerryz123 , I'll give it a try

**Comment by Yuxin-Yu** [comment]
Hi @jerryz123 ,I found that when using the default Banked L2, direct access to DRAM can be achieved through WithExtMemSbusBypass configuration. However, when using Inclusive L2, the WithExtMemSbusBypass configuration does not work. Is this normal?
