### ISSUE TITLE
Error while executing the command " ./build-setup.sh "

### ISSUE THREAD

**Issue by waseem-10xe** [ucb-bar/chipyard#1975]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: a6a6a6

### OS Setup

Ex: Output of `uname -a` + `lsb_release -a` + `printenv` + `conda list`

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

When I execute the ./build-setup.sh command i get this:
![image](https://github.com/user-attachments/assets/a876059a-b75f-4d4a-8d88-a3defe0a721c)

### Expected Behavior

 Built successfully.

**Comment by JFKTRSDAKIDHIKA** [comment]
i also run in to thuis problem.
the way i address this is that i rrmove the chipyard fold and clone a new one and ckeckout to branch HEAD instead of branch 1.4

**Comment by waseem-10xe** [comment]
Yes I also have solved the error by running the commands ./build-setup.sh riscv-tools -s 9
If I skip the step 9 then build setup is done an d work properly.
