### ISSUE TITLE
VSLI flow needs a different way of cloning tech plugins

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/chipyard#208]
We should also have a .gitignore that blanket ignores vlsi stuff, with some documentation that it is expected that you'll remove this on your chip-specific forks.

**Comment by alonamid** [comment]
The gitignore stuff was fixed, and the init-vlsi script will init a tech plugin, but this still requires a docs update since it's not mentioned anywhere other than the ASAP7 tutorial. Related to other VLSI docs issues such as #692

**Comment by harrisonliew** [comment]
#1324 includes docs clarifying new install/update scripts.
