### ISSUE TITLE
Error Generating Bitstream for VCU118 with RocketVCU118Config

### ISSUE THREAD

**Issue by yasnakateb** [ucb-bar/chipyard#2118]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.10.0

### OS Setup

uname -a
Linux teknopro1 6.8.0-48-generic ~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 GNU/Linux

### Current Behavior

I am encountering an issue when trying to generate the bitstream for the VCU118 board with the RocketVCU118Config. Below is the error message I receive:

make SUB_PROJECT=vcu118 CONFIG=RocketVCU118Config bitstream
Running with RISCV=/home/.conda-env/riscv-tools
mkdir -p /home/chipyard/fpga/generated-src/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config
(set -o pipefail && cd /home/chipyard && java -cp /home/chipyard/.classpath_cache/chipyard.jar chipyard.Generator --target-dir /home/chipyard/fpga/generated-src/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config --name chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config --top-module chipyard.fpga.vcu118.VCU118FPGATestHarness --legacy-configs chipyard.fpga.vcu118:RocketVCU118Config | tee /home/chipyard/fpga/generated-src/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config.chisel.log)
**Error: Option --top-module failed when given 'chipyard.fpga.vcu118.VCU118FPGATestHarness'**
make: *** [common.mk:132: /home/chipyard/fpga/generated-src/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config/chipyard.fpga.vcu118.VCU118FPGATestHarness.RocketVCU118Config.fir] Error 1

I have already checked the path to Vivado and confirmed it is set correctly. However, the error persists.

### Expected Behavior

The bitstream should be successfully generated for the VCU118 board with the RocketVCU118Config.

**Comment by jerryz123** [comment]
Delete the `chipyard/.classpath_cache` directory (it's a hidden directory), then try again.

**Comment by yasnakateb** [comment]
It worked! Thanks!
