### ISSUE TITLE
Installing on macOS does not work

### ISSUE THREAD

**Issue by mehnadnerd** [ucb-bar/chipyard#212]
Installation under macOS does not work, as the toolchains fail to build. I believe this is caused by mismatches between GNU and BSD tools, and/or GCC/Clang interoperability issues. There is a homebrew RISCV-tools package at https://github.com/riscv/homebrew-riscv (I haven't tested it yet), it would be helpful to link to it or provide notice that this may not work properly under macOS.

The errors in making are:
make[1]: *** [all-gcc] Error 2
make: *** [stamps/build-gcc-newlib-stage1] Error 2
I can't find the original errors since there are many, many warnings Clang throws when compiling GCC and related tools.

**Comment by abejgonzalez** [comment]
Addressed in https://chipyard.readthedocs.io/en/dev/index.html
