### ISSUE TITLE
FireChip TestSuite Cleanup

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/chipyard#217]
https://github.com/ucb-bar/chipyard/blob/c63fbfa4602dab11e71e1cba564d14f2e8766905/generators/firechip/src/main/scala/Generator.scala#L24-L67

I believe this can now be refactored into the Generator itself. So now there is no need to create a new trait that gets added.

**Comment by zhemao** [comment]
These variables don't appear to be used anymore. So yeah, we should delete these, along with the special regression-tests variable in common.mk.

**Comment by zhemao** [comment]
Resolved by #226
