### ISSUE TITLE
Question about measuring how many cycles the program takes with RISC-V "rdcycle" instruction.

### ISSUE THREAD

**Issue by nenjeff** [ucb-bar/chipyard#30]
Hello,

I have referenced issue #7.
(1). I use the method RISC-V "rdcycle" instruction to measure how many cycles the program takes.
And it gets:
![image](https://user-images.githubusercontent.com/37441387/38812599-526958b0-41bf-11e8-8d30-7c9eb9cca6e3.png)

(2). I have also checked out with .vcd file and make sure above method get correct result.
It complete in 86975(ns), and the clock period is 2(ns).
Therefor, the program takes about 43487 cycles to complete.
image
![image](https://user-images.githubusercontent.com/37441387/38812618-629e3232-41bf-11e8-859d-6bf8708b8578.png)

Why the results differ dramatically? Or there is something I misunderstand?

**Comment by zhemao** [comment]
Are you saying that the simulation terminated 43487 cycles in?

The point at which the rdcycle instruction executes is long before the simulation terminates.

**Comment by nenjeff** [comment]
"Are you saying that the simulation terminated 43487 cycles in?"
->Yes
