### ISSUE TITLE
After running a test, the console output can't be seen unless `reset` is run

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/chipyard#309]
> Hmm. For some reason, after running a test, the console output can't be seen unless I `reset`. Im looking into it for now.

This is only a issue with the newer VCS version, if that helps

_Originally posted by @jerryz123 in https://github.com/ucb-bar/chipyard/pull/308#issuecomment-542326124_

**Comment by jerryz123** [comment]
This seems like a Millennium environment issue, rather than a chipyard issue, but we can track it here

**Comment by seldridge** [comment]
FWIW, this is pretty long-standing in Rocket Chip. I've noticed it and @ccelio has also experienced it.

Thanks for opening a tracking issue about it!
