### ISSUE TITLE
Adding sifive-cache to RocketChip

### ISSUE THREAD

**Issue by gdessouky** [ucb-bar/chipyard#313]
When trying to compile the sifive-cache scala files, I get the error:   class OMInclusiveCache needs to be abstract, since method memories in trait OMCache of type => Seq[freechips.rocketchip.diplomaticobjectmodel.model.OMSRAM] is not defined

I haven't changed any of the scala files.

**Comment by jerryz123** [comment]
This sounds like a version incompatibility issue between sifive-cache and rocketchip. What commits of each are you using? The commits packaged together in Chipyard are always compatible.

**Comment by gdessouky** [comment]
Yup, you're right, fixed it, thanks!
