### ISSUE TITLE
How to add custom ISA extensions to Rocket and BOOM Core?

### ISSUE THREAD

**Issue by vargandhi** [ucb-bar/chipyard#333]
Hi,
I'm trying to add custom ISA extensions to Rocket/BOOM core. Are there any relevant tutorial videos or slides available?

**Comment by abejgonzalez** [comment]
Sorry, I don't believe there are any slides/videos on either of these things. If you are looking to add an accelerator, I would look into using the RoCC interface/instructions to attach an accelerator.
