### ISSUE TITLE
Error for "make CONFIG=HwachaLargeBoomAndHwachaRocketConfig"

### ISSUE THREAD

**Issue by nicolast0604** [ucb-bar/chipyard#352]
[error] tile.scala:302: Vec and Seq being bulk connected have different lengths! in class boom.common.BoomTileModuleImp
[warn] There were 31 deprecated function(s) used. These may stop compiling in a future release - you are encouraged to fix these issues.
[warn] Line numbers for deprecations reported by Chisel may be inaccurate; enable scalac compiler deprecation warnings via either of the following methods:
[warn]   In the sbt interactive console, enter:
[warn]     set scalacOptions in ThisBuild ++= Seq("-unchecked", "-deprecation")
[warn]   or, in your build.sbt, add the line:
[warn]     scalacOptions := Seq("-unchecked", "-deprecation")
[error] There were 1 error(s) during hardware elaboration.
[error] (run-main-0) chisel3.internal.ChiselException: Fatal errors during hardware elaboration
[error] chisel3.internal.ChiselException: Fatal errors during hardware elaboration
[error]         at chisel3.internal.throwException$.apply(Error.scala:44)
[error]         at chisel3.internal.ErrorLog.checkpoint(Error.scala:111)
[error]         at chisel3.internal.Builder$.$anonfun$build$2(Builder.scala:345)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error]         at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:341)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error]         at chisel3.internal.Builder$.build(Builder.scala:341)
[error]         at chisel3.Driver$.elaborate(Driver.scala:95)
[error]         at freechips.rocketchip.util.HasGeneratorUtilities.elaborate(GeneratorUtils.scala:59)
[error]         at freechips.rocketchip.util.HasGeneratorUtilities.elaborate$(GeneratorUtils.scala:50)
[error]         at example.Generator$.elaborate(Generator.scala:9)
[error]         at freechips.rocketchip.util.GeneratorApp.circuit(GeneratorUtils.scala:96)[error]         at freechips.rocketchip.util.GeneratorApp.circuit$(GeneratorUtils.scala:96)
[error]         at example.Generator$.circuit$lzycompute(Generator.scala:9)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 111 s, completed Dec 1, 2019 5:28:58 AM
/home/nicolast/chipyard/common.mk:44: recipe for target 'generator_temp' failed
make: *** [generator_temp] Error 1

**Comment by abejgonzalez** [comment]
Hi,

I believe this was fixed with the following BOOM commit:
https://github.com/riscv-boom/riscv-boom/commit/1939935c07096b5d17b340435c10096eba62d13e. The development branch of the repo (`dev`) has this fix but `master` hasn't been bumped yet. You can go ahead and try bumping BOOM to a more recent version, although I don't know if that will cause other issues.
