### ISSUE TITLE
FIRRTL bug

### ISSUE THREAD

**Issue by siyy123** [ucb-bar/chipyard#359]
I'm trying to build Top with DTM and jtag. But FIRRTL failed when Running barstools.tapeout.transforms.GenerateTopAndHarness
Log:
------------------------------------------------------------------------------
Warning: firrtl.Driver is deprecated since 1.2!
Please switch to firrtl.stage.FirrtlMain
------------------------------------------------------------------------------
Total FIRRTL Compile Time: 169021.8 ms
------------------------------------------------------------------------------
Warning: firrtl.Driver is deprecated since 1.2!
Please switch to firrtl.stage.FirrtlMain
------------------------------------------------------------------------------
[error] (run-main-0) firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error] firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error]         at firrtl.Utils$.error(Utils.scala:437)
[error]         at firrtl.Utils$.throwInternalError(Utils.scala:178)
[error]         at firrtl.stage.FirrtlStage.run(FirrtlStage.scala:34)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:140)
[error]         at firrtl.options.Translator.transform$(Phase.scala:140)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:46)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] Caused by: java.util.NoSuchElementException: None.get
[error]         at scala.None$.get(Option.scala:349)
[error]         at scala.None$.get(Option.scala:347)
[error]         at firrtl.transforms.DeadCodeElimination.createDependencyGraph(DeadCodeElimination.scala:174)
[error]         at firrtl.transforms.DeadCodeElimination.run(DeadCodeElimination.scala:297)
[error]         at firrtl.transforms.DeadCodeElimination.execute(DeadCodeElimination.scala:351)
[error]         at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:216)
[error]         at firrtl.Utils$.time(Utils.scala:183)
[error]         at firrtl.Transform.runTransform(Compiler.scala:216)
[error]         at firrtl.SeqTransformBased.$anonfun$runTransforms$1(Compiler.scala:281)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:86)
[error]         at firrtl.SeqTransformBased.runTransforms(Compiler.scala:281)
[error]         at firrtl.SeqTransformBased.runTransforms$(Compiler.scala:280)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 473 s, completed Dec 8, 2019, 1:53:37 PM
/home/siyy123/chipyard/common.mk:60: recipe for target 'firrtl_temp' failed
make: *** [firrtl_temp] Error 1

Config: 
  new WithDTMTop ++
  new freechips.rocketchip.subsystem.WithJtagDTM ++
  new WithBootROM ++
  new freechips.rocketchip.subsystem.WithExtMemSize((1 << 30) * 2L) ++
  new freechips.rocketchip.subsystem.WithNoSlavePort ++
  new freechips.rocketchip.subsystem.WithNoMMIOPort ++
  new freechips.rocketchip.subsystem.WithInclusiveCache ++
  new hwacha.ISCA2016L4Config ++
  new freechips.rocketchip.subsystem.WithNBigCores(1) ++
  new freechips.rocketchip.system.BaseConfig
It will not happen if a Top without DTM is built.

**Comment by colinschmidt** [comment]
Can you retry this on the latest dev commit of chipyard?
We recently updated FIRRTL and perhaps the issue has been fixed.
