### ISSUE TITLE
sbt error downloading semanticdb-scalac

### ISSUE THREAD

**Issue by JaewonHur** [ucb-bar/chipyard#374]
I'm new to chipyard and now following the tutorial in https://chipyard.readthedocs.io

When I follow all the steps and type make in the sims/verilator directory,
sbt emits error downloading org.scalameta:semanticdb-scalac_2.12.4:4.2.3 (Not found)

It seems to be related to the version issue, but I could not solve the problem.
Could you help me?

Thank you.

**Comment by abejgonzalez** [comment]
https://github.com/ucb-bar/chipyard/blob/61ca6fa294526bb20443f15766a374c01071b0b8/variables.mk#L140-L146

In the `SBT ?= ... ++$(SCALA_VERSION)` line it is forcing SBT to use version `2.12.4`. Go ahead and switch `SCALA_VERSION` to `2.12.10`. This is on the `dev` branch so this should be resolved when `master` is updated.
