### ISSUE TITLE
DUT name in TestHarness incorrect

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/chipyard#382]
The DUT instance name in the hierarchy is not getting a proper name (i.e. `dut`, etc) but is instead getting `TestHarness`.

![image](https://user-images.githubusercontent.com/8823803/72642266-c5e3d180-3920-11ea-8019-0dfc51e95811.png)

See the comment on #347 for more discussion on it.

**Comment by jerryz123** [comment]
Resolved by #347
