### ISSUE TITLE
Add ChipTop module layer between TestHarness and Top

### ISSUE THREAD

**Issue by jerryz123** [ucb-bar/chipyard#385]
The `Top` in Chipyard is really a digital-only `Top`. Typically, our chips have had at least one other later of hierarchy above the `DigitalTop`, below the `TestHarness`. This "ChipTop" layer would also contain analog blocks.

It may be useful to create that layer in Chipyard, such that the default designs are more realistic representations of chips that might be taped out.

**Comment by harrisonliew** [comment]
Would it be useful to create some dummy "IO cells" in ASAP7?

**Comment by jwright6323** [comment]
Yes

**Comment by alonamid** [comment]
Resolved by #480
