### ISSUE TITLE
Memory Address where TSI loads binary

### ISSUE THREAD

**Issue by muhammadali201** [ucb-bar/chipyard#39]
At which address the Serial Device loads the program using TSI?
How does rocket-chip know the address to jump to after binary loading is finished?

**Comment by abejgonzalez** [comment]
In the current `project-template` setup, the `bootrom` waits for the serial interface to load the program before executing it (see https://github.com/ucb-bar/testchipip/blob/master/src/main/resources/testchipip/bootrom/bootrom.S). It is specified in the `bootrom` that the start address of the program is at `0x80000000`.

**Comment by abejgonzalez** [comment]
You can also reference this: https://chipyard.readthedocs.io/en/latest/Customization/Boot-Process.html. If your question is answered could you please close your issue!
