### ISSUE TITLE
Adding IceNIC to Design

### ISSUE THREAD

**Issue by mcarman8** [ucb-bar/chipyard#391]
I am attempting to add the IceNIC to my design, and in the documentation in section 3.5, it says to add the "WithIceNIC" config mixin. However, I cannot find any references to the configuration in the chipyard project. Is there something I am missing, or do I potentially have an incomplete install of chipyard?

**Comment by abejgonzalez** [comment]
Sorry for the late response. Currently `master` doesn't have the `WithIceNIC` mixin in the `example` section of Chipyard. It looks like that is just a mistake in the documentation. However, if you look at `firechip` you can see that there is a `WithNICKey` mixin that adds the NIC to the system. 

With that being said, in the next couple days we were looking to bump the `dev` branch to `master`. In that, there is a `WithIceNIC` mixin in the `example` section: https://github.com/ucb-bar/chipyard/blob/d7d7c79c22cc2aa982da67725ec096fc5e616219/generators/example/src/main/scala/RocketConfigs.scala#L217
