### ISSUE TITLE
Why TinyCore(CONFIG=TinyConfig) cannot use RoCC interface, but BigCores and SmallCores can?

### ISSUE THREAD

**Issue by ckj119940887** [ucb-bar/chipyard#404]
I create a config in rocket-chip/src/main/scala/system/Configs.scala, which is:
class tinyCoreWithRoCC extends Config(new WithRoccExample ++ new TinyConfig)

And I use the xcustom.h (https://github.com/IBM/rocc-software) to create my own test program.
#include <stdio.h>
#include "xcustom.h"
    
#define doTest(rocc_rs1, rocc_rs2) \
	ROCC_INSTRUCTION_0_R_R(1, rocc_rs1, rocc_rs2, CP_TEST, 11, 12)

void main() {
  int a, b, c; 
  a = 5;
  b = 2;

  doTest(a, b);
  printf("the outcome is %d\n", c);
}

Then I use the verilator to test the above program, but in TinyCore(TinyConfig), I found the RoCC custom instruction cannot be decoded in processor core and executed in coprocessor. Specially, I didn't find the custom instruction sent to processor core(I print all raw instruction from ICache). But this program works on RoccExampleConfig(Bigcores).

**Comment by alonamid** [comment]
Since TinyCore is a built-in Rocketchip config which has not been used within Chipyard so far, we would recommend asking this question about TinyCore+RoCC within the Rocket Chip project (https://github.com/chipsalliance/rocket-chip/issues)
