### ISSUE TITLE
Can't use a config without uart

### ISSUE THREAD

**Issue by siyy123** [ucb-bar/chipyard#423]
when trying to use a config without uart the compiler fails with the message during elaboration.

> [error] Caused by: java.lang.IllegalArgumentException: requirement failed: Key PeripheryUARTKey is not defined in Parameters

it seems that in recent versions the chip must have a uart periphery. without it the compiler would fail.

**Comment by jerryz123** [comment]
You can add a WithNoUART mixin that sets the UARTKey to Nil, like WithNoGPIO.

Sorry we'll add this mixin to the next version of chipyard by default.

**Comment by alonamid** [comment]
Resolved by #536 (in the development branch. Will appear on master in the next release)
