### ISSUE TITLE
Issue with building a DTM+JTAG 

### ISSUE THREAD

**Issue by rajeshkrmeena** [ucb-bar/chipyard#430]
I build with "make CONFIG=jtagRocketConfig". It generated the DTM-JTAG module with ROCKET. But, when I tried to simulate it but it returning busy when trying to read/write a DM register except for DMCONTROL (0x10) register. I looked into inside also found that dmi_req_resp_valid is not returned/asserted if accessing a DM register except DMCONTROL. 

A screenshot, debug module,  is attached.
![Screenshot from 2020-02-13 11-12-52](https://user-images.githubusercontent.com/46475847/74404828-95288680-4e51-11ea-9d3c-5e65cb24064a.png)

**Comment by colinschmidt** [comment]
Are you connecting to it via openocd? 
Did you follow the steps here: 
https://chipyard.readthedocs.io/en/latest/Advanced-Concepts/Chip-Communication.html#using-the-jtag-interface

**Comment by rajeshkrmeena** [comment]
Yes, I want to connect it via Openocd. Yes, I followed all the steps.
