### ISSUE TITLE
 /root/chipyard/common.mk:68: recipe for target 'firrtl_temp' failed make: *** [firrtl_temp] Error 137

### ISSUE THREAD

**Issue by Crosshairs** [ucb-bar/chipyard#439]
![捕获3](https://user-images.githubusercontent.com/43806118/74937387-e2df5900-5426-11ea-9068-e0e83683ff05.PNG)
When I run :
make CONFIG=Sha3RocketConfig run-binary-debug BINARY=/root/chipyard/generators/sha3/software/benchmarks/bare/sha3-rocc.riscv (in the chipyard/sims/verilator)

**Comment by Crosshairs** [comment]
I'm sorry.  I run success!

**Comment by colinschmidt** [comment]
Sounds like you got it working. Closing for now.

**Comment by CoCoMilkyWay** [comment]
> I'm sorry. I run success!

How did you do it? I still failed :(
