### ISSUE TITLE
Problem compiling riscv-gdb: config.h must be #included before system headers

### ISSUE THREAD

**Issue by tehom** [ucb-bar/chipyard#494]
**Impact**: software

**What is the current behavior?**
 build-toolchains.sh has fatal error building riscv-gdb
**What is the expected behavior?**
Successful compile
**Please tell us about your environment:**

Debian Linux 4.9.0-9-amd64
Compiler gcc
Installed all the packages that
https://chipyard.readthedocs.io/en/latest/Chipyard-Basics/Initial-Repo-Setup.html#initial-repository-setup recommended

Ran build-toolchains.sh
The compile failed on riscv-gdb

Error message:

 In file included from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-basics.h:30,
		  from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-arange.c:24:
 ../../bfd/config.h:7:4: error: #error config.h must be #included before system headers
  #  error config.h must be #included before system headers
     ^~~~~

Compilation command (issued by build-toolchains.sh) was:
/usr/bin/gcc -DHAVE_CONFIG_H -DWITH_DEFAULT_MODEL='"RV64G"' -DWITH_ALIGNMENT=NONSTRICT_ALIGNMENT -DWITH_TARGET_WORD_BITSIZE=64 -DWITH_TARGET_BYTE_ORDER=BFD_ENDIAN_LITTLE   -DDEFAULT_INLINE=0   -Wall -Wdeclaration-after-statement -Wpointer-arith -Wpointer-sign -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wmissing-prototypes -Wdeclaration-after-statement -Wempty-body -Wmissing-parameter-type -Wold-style-declaration -Wold-style-definition -Wformat-nonliteral      -I. -I/home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv -I../common -I/home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common -I../../include -I/home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../../include -I../../bfd -I/home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../../bfd -I../../opcodes -I/home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../../opcodes  -g -O2 -c -o sim-arange.o -MT sim-arange.o -MMD -MP -MF .deps/sim-arange.Tpo /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-arange.c

I did a little digging, and other people have reported similar issues with gdb.  It's not clear that there's any sensible way to satisfy the failing test.

The offending file, config.h, is actually not part of the source but is built from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/riscv-gdb/bfd/configure.ac

I was able to hack past it by commenting out the lines in configure.ac
that create the failing test.  Running this got it to compile past that point without obvious consequences, but other issues kept me from compiling riscv-gdb.

**Comment by abejgonzalez** [comment]
Closing for now since there is no update on this.
