### ISSUE TITLE
Problem running build-toolchains.sh: Error, WITH_PROFILE not defined

### ISSUE THREAD

**Issue by tehom** [ucb-bar/chipyard#495]
**Impact**: software

**What is the current behavior?**
 build-toolchains.sh has fatal error building riscv-gdb
**What is the expected behavior?**
Successful compile
**Please tell us about your environment:**

Debian Linux 4.9.0-9-amd64
Compiler gcc
Installed all the packages that
https://chipyard.readthedocs.io/en/latest/Chipyard-Basics/Initial-Repo-Setup.html#initial-repository-setup recommended
Had hacked past an earlier riscv-gdb compile problem by changing configure.ac to remove a test from config.h

**Other information**

Ran build-toolchains.sh
The compile failed on riscv-gdb

File being compiled was
 /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-command.c

Error message was
 In file included from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-base.h:88,
		  from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/sim-main.h:26,
		  from /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-close.c:21:
 /home/tehom/projects/ic-fab/chipyard/toolchains/riscv-tools/riscv-gnu-toolchain/build/../riscv-gdb/sim/riscv/../common/sim-profile.h:24:1: warning: data definition has no type or storage class
  Error, WITH_PROFILE not defined.

Looking at the source, profile.h simply fires off this error when it doesn't see WITH_PROFILE.  acinclude.m4 derives it from something called sim_profile.  I found no hint as to where sim_profile should have come from.  

At some point in the source we have #undef WITH_PROFILE; it's in multiple places but all of them seem derived from config.in.  Not sure how that's interacting with this problem.

I did notice in the ChangeLog that WITH_PROFILE was removed 4 years ago:
ChangeLog 
 2016-01-10  Mike Frysinger  <vapier@gentoo.org>
	* sim-config.h (SIM_HAVE_ENVIRONMENT, WITH_ENVIRONMENT,
	DEFAULT_ENVIRONMENT, WITH_DEBUG, WITH_TRACE, WITH_PROFILE,
	WITH_ASSERT, WITH_STDIO): Delete.

**Comment by abejgonzalez** [comment]
Closing for now since there is no update on this.
