### ISSUE TITLE
Including Prerequisites in "Quick Start" or Script

### ISSUE THREAD

**Issue by Matthias-Raudonis** [ucb-bar/chipyard#514]
**Impact**: software

**Description**

Following the Quick Start guide from a clean Ubuntu 18 LTS install, one encounters repeated compile errors because some packages are missing. 

In "1.4. Initial Repository Setup" I found some prerequisites are mentioned. 

I am suggesting a reference from the Quick Start Section to the above section. Why not make a script and include it into the Quick Start Process?

**What is a motivating example for changing the behavior?**
It takes a much shorter time to compile if there are no repeated errors.

**Comment by Matthias-Raudonis** [comment]
Note: This was the cause of issues #455 and #436

**Comment by alonamid** [comment]
Fixed by #518
