### ISSUE TITLE
How to enable RoCC interface Interrupt?

### ISSUE THREAD

**Issue by ckj119940887** [ucb-bar/chipyard#522]
I implement a coprocessor based on RoCC interface. But the CSR module didn't have any response when rocc interrupt raised. I'd like to know whether need I enable some bits in CSR (Like support RoCC instruction, set XS bits in mstatus).

**Comment by jerryz123** [comment]
Sorry for the late reply. You probably need to set the right bit in MIE to enable the RoCC interrupts.
