### ISSUE TITLE
RTL Simulation Hangs at WFI in Designs Using AsyncReset

### ISSUE THREAD

**Issue by davidbiancolin** [ucb-bar/chipyard#529]
During the rocket-chip bump I refactored ChipTop to support both synchronous and asynchronous reset in a single ChipTop calss. During my work I noticed that the targets that use an asynchronous reset that was caught and synchronized wouldn't correctly run assembly tests.  I'm opening this issue to track it's bring up. 

Set `p(GlobalResetScheme) = GlobalResetAsynchronous` to reproduce this. 

I think the full-async-reset scheme is broken but that's no fault of our own. It might make sense to just remove it. 

**Impact**: rtl 

**What is the current behavior?**
- The design spins at WFI

**What is the expected behavior?**
- Should be able to run all assembly tests when using and AsyncReset scheme

**Please tell us about your environment:**
- Millennium

**Other information**
- This did not seem to work before the RC bump.

**Comment by jerryz123** [comment]
I believe the diplomatic ResetSynchronizers fixed this issue. The current designs use AsyncReset and behave correctly.

https://github.com/ucb-bar/chipyard/pull/703
