### ISSUE TITLE
Heterogeneous-SoCs.rst should use List() or ::, not ++

### ISSUE THREAD

**Issue by cousteaulecommandant** [ucb-bar/chipyard#535]
`docs/Customization/Heterogeneous-SoCs.rst` states this way of creating multiple dissimilar Rockets:
```scala
val rocketTile0 = RocketTileParams(...) // params for rocket core 0
val rocketTile1 = RocketTileParams(...) // params for rocket core 1
rocketTile0 ++ rocketTile1
```
However, you can't use the `++` operator (list concatenation) on RocketTileParams, since they are not lists nor have a `++` method defined (as of v1.2.0); trying to do so results in an error.
What is needed is to _create_ a list:
```scala
List(rocketTile0, rocketTile1) // more readable option
```
or
```scala
rocketTile0 :: rocketTile1 :: Nil // "Lisp-style" list creation
```

**Comment by abejgonzalez** [comment]
Thanks for the catch. You are correct. `BoomTilesKey` and `RocketTilesKey` both take a `Seq` of `<Boom/Rocket>TileParams` so you can use `Seq`, `List`, etc. I went ahead and PR'ed a fix.
