### ISSUE TITLE
How RocketCore/BOOM do energy, area modeling?

### ISSUE THREAD

**Issue by meton-robean** [ucb-bar/chipyard#566]
Hi, I have implemented a custom accelerator based on RocketChip using RoCC and ran verilator simulation successfully.  Now I want to do energy, area modeling on my acceleratored RocketCore? Is there any tool to do that?  Thanks!

**Comment by alonamid** [comment]
Energy and area are usually estimated by going through the Hammer VLSI flow (synthesis and physical design).
Chipyard and Hammer include plug-ins for the open-source ASAP7 PDK for such estimations, but you still need access to commercial EDA tools such as Cadence. 
For higher-fidelity estimations, commercial PDKs are usually preferred if you have access (https://hammer-vlsi.readthedocs.io/en/latest/Hammer-Basics/Hammer-Overview.html). 

There is also currently an open PR (#608 ) to support open-source OpenRoad tools for the VLSI flow.
