### ISSUE TITLE
[docs] ScratchpadRocketConfig description in Memory-Hierarchy.rst doesn't match its behavior

### ISSUE THREAD

**Issue by cousteaulecommandant** [ucb-bar/chipyard#567]
`docs/Customization/Memory-Hierarchy.rst` section "The L1 Caches" shows an example code of how to use a scratchpad (on-chip memory).  However, the code doesn't reflect what the description says.

What the description suggests:
* The scratchpad replaces the L1 data cache (this is what `With1TinyCore` does by setting `RocketTilesKey` -> `dcache` -> `scratch`).
* No L2 by setting number of banks to 0 (which can be achieved with `WithNBanks(0)`).
* No memory bus by setting the number of channels to 0 (`WithNMemoryChannels(0)`).
* Only a single core allowed and no external memory allowed.
* Core -> L1D Scratchpad

What the code does:
* The scratchpad hangs from the `mbus` (uses `WithBackingScratchpad`); it does NOT use L1 scratchpad.
* L2 present (`WithInclusiveCache` in use; diplomacy graph shows one L2 node).
* No memory port (`WithNoMemPort`), BUT memory bus present.
* IIUC there's no reason to limit this system to one core and remove external memory, as long as there's no address overlap.  (I haven't tried and I may be wrong.)
* Core -> L1I/D cache -> TileBus -> SystemBus -> L2 cache -> MemoryBus -> BackingScratchpad

I think both cases are useful.  The latter simply replaces the external memory with one generated inside the Top and connected to the mbus directly (which is something I wanted to do because it seemed like the logical way to provide on-chip memory, and the example has really helped me once I understood what it did), whereas the former provides a "tightly coupled memory" that is close to the core but cannot be shared among cores.  Therefore, it might be a good idea to document both cases (add an example for the former and a description for the latter).
Nevertheless, the `WithBackingScratchpad` example and documentation should be moved outside of section 6.9.1 ("The L1 Caches"), since it has nothing to do with L1, to section 6.9.5 ("The Outer Memory System") or to a new section.

**Comment by abejgonzalez** [comment]
Based on the `dev` branch, this was changed accidentally from the description to a different configuration (which was similarly named but not used for the same purpose).

Faulty commit:
https://github.com/ucb-bar/chipyard/commit/708a5fb9a610c6f003d3d78f3657cd8f125f879f

Original code that matched the description:
```
    class ScratchpadSmallRocketConfig extends Config(
         new chipyard.iobinders.WithUARTAdapter ++
         new chipyard.iobinders.WithTieOffInterrupts ++
         new chipyard.iobinders.WithSimAXIMem ++
         new chipyard.iobinders.WithTiedOffDebug ++
         new chipyard.iobinders.WithSimSerial ++
         new testchipip.WithTSI ++
         new chipyard.config.WithNoGPIO ++
         new chipyard.config.WithBootROM ++
         new chipyard.config.WithUART ++
         new chipyard.config.WithL2TLBs(1024) ++
         new freechips.rocketchip.subsystem.WithNMemoryChannels(0) ++
         new freechips.rocketchip.subsystem.WithNBanks(0) ++
         new freechips.rocketchip.subsystem.WithScratchpadsOnly ++
         new freechips.rocketchip.subsystem.WithNoMMIOPort ++
         new freechips.rocketchip.subsystem.WithNoSlavePort ++
         new freechips.rocketchip.subsystem.WithNExtTopInterrupts(0) ++
         new freechips.rocketchip.subsystem.WithNSmallCores(1) ++
         new freechips.rocketchip.system.BaseConfig)
```

Ill go ahead and try to fix up the documentation. Good catch.
