### ISSUE TITLE
Clock-cycle latency sifive L2 inclusive cache

### ISSUE THREAD

**Issue by gdessouky** [ucb-bar/chipyard#602]
I'm trying to figure out the clock cycle latency for the L2 inclusive cache from sifive. I can't seem to find it documented anywhere. Can anyone help? Thanks!

**Comment by jerryz123** [comment]
This depends on the configuration of the cache, as well as the configuration of the bus topology and tiles. I recommend trying to measure this yourself on the designs you are interested in.

On a simple design, I see 10-cycles of latency between refill-request and refill-completion, as observed from a L1 cache.
