### ISSUE TITLE
Can't build esp-tools

### ISSUE THREAD

**Issue by shirlynan** [ucb-bar/chipyard#604]
I got errors when running ./scripts/build-toolchains.sh riscv-tools esp-tools:

/home/chipyard/esp-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lstdc++
/home/chipyard/esp-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lgcc_s

How could I solve it?
Thanks for your help.

**Comment by alonamid** [comment]
I believe the build-toolchains.sh script takes only one argument, not two.
You need to run the script once for each of the toolchains.

**Comment by shirlynan** [comment]
> I believe the build-toolchains.sh script takes only one argument, not two.
> You need to run the script once for each of the toolchains.

Thanks for your reply. However,  even if I only use one argument, I got same errors. I can't compile riscv-tools either.

chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lstdc++
chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lgcc_s

**Comment by yzt000000** [comment]
> > I believe the build-toolchains.sh script takes only one argument, not two.
> > You need to run the script once for each of the toolchains.
> 
> Thanks for your reply. However, even if I only use one argument, I got same errors. I can't compile riscv-tools either.
> 
> chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lstdc++
> chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lgcc_s

how to recover it， I had met the same problem

**Comment by shirlynan** [comment]
> > > I believe the build-toolchains.sh script takes only one argument, not two.
> > > You need to run the script once for each of the toolchains.
> > 
> > 
> > Thanks for your reply. However, even if I only use one argument, I got same errors. I can't compile riscv-tools either.
> > chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lstdc++
> > chipyardtest/chipyard/riscv-tools-install/lib/gcc/riscv64-unknown-linux-gnu/9.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find -lgcc_s
> 
> how to recover it， I had met the same problem

Sorry, a long time has passed, I've forgotten how I solved it. But I vaguely remember that, I seemed to have reinstalled the entire toolchain or upgraded the gcc version. It would be great if you could try again and tell me if it works.

**Comment by mbs0221** [comment]
I had met similar problems when running the build-toolchains.sh script for riscv-tools as following:
`$ ./scripts/build-toolchains.sh riscv-tools`
