### ISSUE TITLE
About IceNet

### ISSUE THREAD

**Issue by bg193** [ucb-bar/chipyard#623]
What is the status of the IceNet project，very little information about it，did IceNet is finished？

**Comment by zhemao** [comment]
Can you elaborate on what you mean by "finished"?

IceNet is feature complete and stable. There is ongoing research using it for distributed architecture research, although not with a specific focus on IceNIC features. We will continue to fix bugs, and potentially add features if they are found to be necessary within the research work.

**Comment by bg193** [comment]
> Can you elaborate on what you mean by "finished"?
> 
> IceNet is feature complete and stable. There is ongoing research using it for distributed architecture research, although not with a specific focus on IceNIC features. We will continue to fix bugs, and potentially add features if they are found to be necessary within the research work.

Where is the difference between IceNet and Ethernet MAC?  If  IceNet connect PHY module can access ethernet?

**Comment by zhemao** [comment]
IceNet provides an Ethernet MAC, yes. If you attach it to a PHY (assuming compatible interfaces), you can connect your SoC to the internet.

**Comment by a0u** [comment]
> IceNet provides an Ethernet MAC, yes. If you attach it to a PHY (assuming compatible interfaces), you can connect your SoC to the internet.

Adding support for MII could be an interesting project for someone.
