### ISSUE TITLE
Can I use firesim locally with a FPGA connected?

### ISSUE THREAD

**Issue by siyy123** [ucb-bar/chipyard#631]
Can I use firesim locally if I have a FPGA accelerator card connected?

**Comment by davidbiancolin** [comment]
Not presently, but we hope to have local board support in a future release.

What card do you have?

**Comment by siyy123** [comment]
> Not presently, but we hope to have local board support in a future release.
> 
> What card do you have?

A Xilinx Kintex-7 325T.

**Comment by abejgonzalez** [comment]
Closing since this is more suited to the FireSim repo/mailing list: https://github.com/firesim/firesim
