### ISSUE TITLE
How to use the latest riscv-boom in chipyard

### ISSUE THREAD

**Issue by hyf6661669** [ucb-bar/chipyard#638]
It seems that the submodule ```chipyard/generators/boom``` points to an older version of boom, but I want to use the latest version (SonicBoom). Could you please tell me how to achieve it ? Thanks!

![image](https://user-images.githubusercontent.com/18757974/89107353-178a1e80-d463-11ea-8775-715422bd94ca.png)

**Comment by jerryz123** [comment]
Oops, it points to a commit of BOOM right before we tagged the 3.0 release. The version there is still SonicBOOM/

**Comment by hyf6661669** [comment]
> Oops, it points to a commit of BOOM right before we tagged the 3.0 release. The version there is still SonicBOOM/

If I want to use another version of BOOM, what should I do?

**Comment by jerryz123** [comment]
What version of BOOM do you want to use?

**Comment by hyf6661669** [comment]
> What version of BOOM do you want to use?

 For example, if I want to use a particular commit hash of BOOM, what should I do?

**Comment by jerryz123** [comment]
You can go into the submodule and git checkout the commit hash you want. Keep in mind that you will run into version incompatibilities if you choose very old commits.

**Comment by hyf6661669** [comment]
> You can go into the submodule and git checkout the commit hash you want. Keep in mind that you will run into version incompatibilities if you choose very old commits.

Thanks.
