### ISSUE TITLE
coverage file generation

### ISSUE THREAD

**Issue by farhanaslam-lm** [ucb-bar/chipyard#640]
Hi,
There is ccover invoked in ICache, DCache, TLB, and PTW of Rocket-Chip. The purpose of these is to generate cover-points for verification. But these points did not generate. Is there any method to generate the coverage file?

**Comment by alonamid** [comment]
I believe you will probably get a better answer if you ask this question in the [Rocket-Chip repo](https://github.com/chipsalliance/rocket-chip), but I can try giving some context from a different perspective.

When I last looked at the Rocket-Chip cover points, the cover function is an unimplemented interface. This means that while the cover-points are indeed embedded in the codebase, what you do with these cover points depends on the backend you implement for them. 
For example, in [FireSim](https://github.com/ucb-bar/chipyard/blob/c576a7e76717376b7a2cbbc0a531f51382ff87f1/generators/firechip/src/main/scala/FireSim.scala#L32), one of the uses for these cover points is to [generate FIRRTL annotations which then insert performance counters](https://github.com/firesim/firesim/blob/c2d8e3a46e59222e115a1fdaa7267592e1d3c503/sim/midas/src/main/scala/midas/passes/AutoCounterCoverTransform.scala#L26) for the signals covered by the cover points.

I am not familiar with a coverage file generation backend, but maybe perhaps some other Rocket-Chip maintainers or users can provide better answers.
