### ISSUE TITLE
deploy the Trusted execution environment（TEE） on BOOM

### ISSUE THREAD

**Issue by hz1490919302** [ucb-bar/chipyard#642]
I want to deploy a TEE called Keystone on BOOM . I have built BOOM and got a file chipyard/sims/verilator/simulator-chipyard-LargeBoomConfig, I can use it to execute some riscv programs. Then how should I deploy TEE to it

**Comment by dayeol** [comment]
Please refer to https://github.com/keystone-enclave/keystone/issues/199 for further discussion
