### ISSUE TITLE
How to extend memory port address width to 64-bit in chipyard-1.3 ?

### ISSUE THREAD

**Issue by huoxinglaizhe** [ucb-bar/chipyard#658]
I tried to modify base address of memory port to 64-bit, but got a lot of errors.

class WithDefaultMemPort extends Config((site, here, up) => {
  case ExtMem => Some(MemoryPortParams(MasterPortParams(
                 //  base = x"8000_0000",
                      base = x"1000_0000_8000_0000",    // up to 64-bit
                      size = x"1000_0000",
                      beatBytes = site(MemoryBusKey).beatBytes,
                      idBits = 4), 1))
})

**Comment by jerryz123** [comment]
The Sv39 virtual memory system which Chipyard systems use for 64-bit designs supports only 56-bits of physical addressing.

**Comment by huoxinglaizhe** [comment]
Thank you very much for your help.
According to your suggestion, I tried to extend base address to 56-bits and got "requirement failed" from BaseTile.scala:131
 ---BaseTile.scala:131-----------------------------------
     val v = maxSVAddrBits
     require(v == xLen || xLen > v && v > paddrBits)
----------------------------------------------------------
when xLen is 64, v is 39, and then physical address bits should be less than 39 ?
This requirement is a little bit strange, and I've no idea how to extend to 56-bits of physical addressing.

**Comment by jerryz123** [comment]
How are you trying to extend the base address?

**Comment by lsteveol** [comment]
Changing the virtual addressing can be done by modifying the `PgLevels` key. sv39 is 3 levels, sv48 is 4, and sv56 is 5. Here is an example `Config` object you can use to change it.

``` scala
class WithSV48VirtAddressing extends Config((site, here, up) => {
  case PgLevels => 4
})

```

The chip infrastructure only uses the amount of addressing defined by the address map (which you are defining via those `PortParams`). Note that you now are causing all (or at least some) of the busses and CPU logic to increase in size to accommodate for the increased addressing requirements. Just realize this _could_ affect your area and timing in a negative way.

**Comment by lsteveol** [comment]
Note that I'm sort of brute forcing the `PgLevels` in my case. I think ideally this parameter would be set diplomatically based on the addressing of the various busses in the design.
