### ISSUE TITLE
Clean multiclock support

### ISSUE THREAD

**Issue by jerryz123** [ucb-bar/chipyard#662]
This issue tracks work towards clean support of multiclock designs. The vision is to use rocketchip's new diplomatic clock graph as an API to determine how to generate and connect clocks for a multiclock design.

- [x] Provide API for driving subsystem's diplomatic clock graph (https://github.com/ucb-bar/chipyard/pull/614)
- [x] Simulated PLL (https://github.com/ucb-bar/chipyard/pull/659)
- [x] Add rocketchip API for specifying requested frequencies of all clocks in the main clock group (https://github.com/chipsalliance/rocket-chip/pull/2618)
- [x] Change existing peripherals to get their clocks from their attachment point (instead of the implicit subsystem clock). This requires rocketchip changes
- [x] Punching out a ChipTop clock into the TestHarness through IOBinders. This is necessary for SimDRAM, SimSerial. (#670 )
- [x] Fix debug module IOBinders to drive chip-side clocks locally (and not through the TestHarness) (#664 )
- [x] ~Change all default configs to have half-freq uncore~. We decided to leave default configs unchanged, to avoid degrading simulation performance too much.

**Impact**: rtl

**Comment by colinschmidt** [comment]
I think we should make SimSerial behave like it does on most test-chips where it provides it's clock off chip to be caught by the testharness and used to synchronize the "serial" data. 
This doesn't change the fact that SimDRAM probably needs this feature (since it isn't meant to be used in the same way as SimSerial).

**Comment by jerryz123** [comment]
I agree we should make Serial more "correct". If that leaves SimDRAM as the only widget for which punching out a clock is necessary, then I think we should just special-case it.
However, if other use cases (like SimNetwork for the NIC) also want to live in TestHarness, and need to be clocked by a chip-internal clock, it may be worth the effort to develop a more generic solution.

**Comment by alonamid** [comment]
Don't forget multi-clock example + documentation

**Comment by jerryz123** [comment]
When this is complete, all default examples will be multi-clock

**Comment by jerryz123** [comment]
Released in 1.4.0
