### ISSUE TITLE
Runtime of the synthesis step in the documentation

### ISSUE THREAD

**Issue by yuzhe630** [ucb-bar/chipyard#671]
Hi, I have been exploring the synthesis flow using Genus. Following this [tutorial](https://chipyard.readthedocs.io/en/latest/VLSI/Tutorial.html#running-the-vlsi-flow), the design is built. Then the next synthesis step (`make syn`) seems to take a very long time (already >100 hours and is still running). I'm wondering if there is an estimated duration for this step. Thanks!

**Comment by colinschmidt** [comment]
The default chipyard config takes only a few hours to get through the whole flow when running on a machine with 8 available cores.

**Comment by yuzhe630** [comment]
Thanks for the information. I guess I need to check my configurations.
