### ISSUE TITLE
make verillog  command fails

### ISSUE THREAD

**Issue by pxs7** [ucb-bar/chipyard#684]
/home/myf/project/tt/chipyard/build.sbt:12: error: not found: value assembly
  test in assembly := {},
          ^
/home/myf/project/tt/chipyard/build.sbt:13: error: not found: value assemblyMergeStrategy
  assemblyMergeStrategy in assembly := { _ match {
  ^
/home/myf/project/tt/chipyard/build.sbt:13: error: not found: value assembly
  assemblyMergeStrategy in assembly := { _ match {
                           ^
/home/myf/project/tt/chipyard/build.sbt:14: error: not found: value PathList
    case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
         ^
/home/myf/project/tt/chipyard/build.sbt:14: error: not found: value MergeStrategy
    case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
                                                ^
/home/myf/project/tt/chipyard/build.sbt:15: error: not found: value MergeStrategy
    case _ => MergeStrategy.first}},
              ^
/home/myf/project/tt/chipyard/build.sbt:183: error: not found: value sbtassembly
  .enablePlugins(sbtassembly.AssemblyPlugin)

**Comment by abejgonzalez** [comment]
Im not sure what the issue is here and there isn't enough information to figure out what you did. Can you give the following information:

```
<!-- choose one -->
**Impact**: rtl | software | unknown | other

**Tell us about your environment:**
*Chipyard Version:* <!-- 1.2.0, Hash: 2c0928 -->
*OS:* <!-- `Linux knight 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` -->
*Other:* <!-- `prior steps taken/documentation followed/...` -->

**What is the current behavior?**

**What is the expected behavior?**

**Other information**
<!-- include detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, ... -->
```
