### ISSUE TITLE
How can I configure the miss penalties for microarchitectural events?

### ISSUE THREAD

**Issue by yunchen-juuuump** [ucb-bar/chipyard#711]
Hi

I would like to configure the Cache/DRAM access latencies manually, but I don't know where can I configure them. I find this [document](https://inst.eecs.berkeley.edu/~cs152/sp18/handouts/lab2-0.2.pdf) that shows the memory access latency(in Table.3). So, where can I configure these latencies in chipyard or Rocket-chip? 

Or these latencies cannot be configured by us manually, and can only be measured by some tools?

Thanks

**Comment by alonamid** [comment]
L2 miss penalties are determined by the backing memory model.
Software RTL simulations can use DRAMSim2 as their backing memory model (when the SimDRAM config fragment is used). The DRAMSim2 [configuration file is found in the testchipip submodule](https://github.com/ucb-bar/testchipip/tree/master/src/main/resources/dramsim2_ini ). You can make copies of the file and edit them with your own custom DramSim2 configuration, and then change the name of the file to your custom one in this [header file](https://github.com/ucb-bar/testchipip/blob/b84509b70ea0d6d01eabf4fb5fd0dbaec1a42121/src/main/resources/testchipip/csrc/mm_dramsim2.h#L98).
FireSim simulations use the [FASED memory model](https://docs.fires.im/en/latest/Advanced-Usage/Generating-Different-Targets.html?highlight=dram#generating-a-different-fased-memory-timing-model-instance) as their backing memory.

L1 miss penalties are determined by the L2 parameters. The way L2 parameters are computed is specified in [this file](https://github.com/sifive/block-inclusivecache-sifive/blob/master/design/craft/inclusivecache/src/Parameters.scala ). You can edit the L2 parameters using arguments to the WithInclusiveCache config fragment.

Measuring latencies should be fairly simple using printfs and/or waveforms in software RTL simulation or FireSim simulations.
