### ISSUE TITLE
can a diplomacy node have :*= and "=* bindings simultaneously

### ISSUE THREAD

**Issue by jerryhethatday** [ucb-bar/chipyard#725]
I read the dipolomacy framework source code of rocketchip generator line by line(Node.scala), and found something confusing in the flexOffset field of the MixedNode class:
https://github.com/chipsalliance/rocket-chip/blob/46c88b71056581a6bf2a0c4febd5ec3d768c6c59/src/main/scala/diplomacy/Nodes.scala#L1001
there is a `require `expression `require (allSink == 0 || allSource == 0,
      s"The nodes ${flexSet.map(_.name)} which are inter-connected by :*=* have ${allSink} :*= operators and ${allSource} :=* operators connected to them, making it impossible to determine cardinality inference direction.")`
I felt that this is confusing, for example: there are node `a, b, c`  and they interconnect like this: `a :*= b  a :=* c`, so according to definition of `allSink `and `allSource`, the `allSink `of node a will be 1, and  `allSource `will also be 1. they are all nonzero, so there will be an exception(the first parameter of the require will be false), right? But I think `a :*= b  a :=* c` should be ok, the connection cardinality between a and b will be determined by a, while the cardinality beween a and c will be determined by c, I felt that this dependency could be  resolved. But why there is a `require `expression.
Also, if node a is a nexusnode, then `a := *b   c :*= a `should also be legal, right? (Indicating the input connection cardinality of node `a` should be decided by `b`, while the output connection cardinality of node `a`  is decided by node `c`, which I think is reasonable.
Is there some info I can get about the general rules of what kind of connection can be resolved and what cant?

**Comment by alonamid** [comment]
Consolidating with chipsalliance/rocket-chip#880
