### ISSUE TITLE
Hella Cache and Dcache difference ?

### ISSUE THREAD

**Issue by Uzair540** [ucb-bar/chipyard#729]
Can you tell me the difference between HellaCache and Dcache?What is the major difference between the two? I have another confusion when we are setting dcache paramters in the config file. What is this cache paramters? Is this data dcache paramters or Hella cache paramters we are setting?
@aswaterman @hcook @yunsup @lsteveol @
![99180831-7aba6b00-274b-11eb-9938-ef2ed9791656](https://user-images.githubusercontent.com/54856325/100710641-d0407a00-33d1-11eb-8324-c533d937b97a.png)

**Comment by jerryz123** [comment]
HellaCache is the abstract class representing a L1 data cache. DCache is an implementation of HellaCache which Rocket uses.
