### ISSUE TITLE
Prebuilt Toolchain Does Not Match Submodules

### ISSUE THREAD

**Issue by davidbiancolin** [ucb-bar/chipyard#732]
**Impact**: software 

**What is the current behavior?**
Uses a significantly older version of the gnu-toolchain that has the gcc bug present. This breaks some SPEC2017 benchmarks. 

**What is the expected behavior?**
Use the submoduled version.

**Other information**
This should be done before the next release. Opening this mostly as a reminder.

**Comment by alonamid** [comment]
Fixed in release 1.4
