### ISSUE TITLE
Bump Scala versions to 2.12.10

### ISSUE THREAD

**Issue by timsnyder-siv** [ucb-bar/chipyard#737]
There is a desire to use portions of chipyard and it's submodules (notably firesim) with vscode+metals.  To do so, @azidar points out that metals wants at least version 2.12.10.

Would it be possible to bump the scala version consistantly to 2.12.latest for the upcoming Chipyard relase?

**Comment by davidbiancolin** [comment]
I think most of the work for this will be done in 3.4 bump.

**Comment by colinschmidt** [comment]
see also: https://github.com/ucb-bar/plsi-mdf/pull/6
and: https://github.com/ucb-bar/barstools/pull/87#issuecomment-742004946

**Comment by timsnyder-siv** [comment]
2.12.10 is probably fine.  When I tried 2.12.12, it looked like the macro-paradise plugin version would also have to be updated to 2.1.1.

**Comment by alonamid** [comment]
Done in the Chipyard 1.4 release
