### ISSUE TITLE
Speed up SBT

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/chipyard#74]
Currently there are 4 SBT calls whenever building RTL. Find a way to simplify the build process to build faster.

- Reduce SBT calls to 2 (1. Gen Sim Files, Normal Elaboration, 2. GenTop, Harness)
- Other?

**Comment by colinschmidt** [comment]
I think you could have a single sbt call if you can do some of the scripty stuff from the sbt CLI. But 2 should be possible without any fancy stuff.

**Comment by jerryz123** [comment]
https://github.com/freechipsproject/firrtl/issues/1090 will let us combing GenerateTop and GenerateHarness phases into one call

**Comment by abejgonzalez** [comment]
Solved partly by #168 (`GenerateTopAndHarness` called together)
