### ISSUE TITLE
Update comment for chipyard.GenerateReset

### ISSUE THREAD

**Issue by timsnyder-siv** [ucb-bar/chipyard#741]
https://github.com/ucb-bar/chipyard/blob/8836f84c79772e2cf9b8fc9118fb862ed2cce9a7/generators/chipyard/src/main/scala/Clocks.scala#L18-L22

@jerryz123 after #703 , the comment above is really confusing.  I just spent awhile looking around for what happened to `GlobalResetScheme` and it doesn't exist anymore.  We should update this comment or delete it.

**Comment by jerryz123** [comment]
Whoops, sorry about that.

**Comment by timsnyder-siv** [comment]
Not a huge deal.  Just thought I might save others the same confusion. :)
