### ISSUE TITLE
An ERROR occured when running"./scripts/build-toolchains.sh"

### ISSUE THREAD

**Issue by First-Killer** [ucb-bar/chipyard#743]
I want to build the chipyard on the Ubuntu18.04,When I run the `./scripts/build-toolchains.sh`,I got an  Error which is `/home/user/anaconda3/lib/libpango-1.0.so：Undefined reference to ‘hb_buffer_set_invisible_glyph’
` after minutes.This looks like a problem with unknown library points.But I don't known how to solove it, Please help me,Thanks!
![1](https://user-images.githubusercontent.com/52058815/102713932-88dd4780-4306-11eb-8981-cc4430c789c1.png)
"对‘hb_buffer_set_invisible_glyph’未定义的引用"means"Undefined reference to 'hb_buffer_set_invisible_glyph'"

**Comment by jerryz123** [comment]
This is an installation issue with QEMU, which is not strictly necessary for the hardware generation and simulation usages of chipyard. You can temporarily try to bypass this issue by commenting out the relevant lines in build-toolchains-nolog.sh

**Comment by First-Killer** [comment]
Thank you!

Jerry Zhao <notifications@github.com> 于 2020年12月30日周三 17:24写道：
