### ISSUE TITLE
How can I shared a FPU between two Rocket cores？

### ISSUE THREAD

**Issue by leizhangpku** [ucb-bar/chipyard#748]

**Comment by jerryz123** [comment]
You can share the FP functional units between two tiles (cores). Note that the FPU module contains FP registers in addition to the FP functional units, so it cannot be shared across tiles.

The challenge with sharing the functional units is piping the signals from one tile to the other. This can probably most easily be implemented with Chisel BoringUtils. In any case, this will require substantial modification to the FPU module, to force one tile to use another tile's FP functional units.
