### ISSUE TITLE
Consider Using CloneModuleAsRecord To Speed Up Elaboration Times 

### ISSUE THREAD

**Issue by davidbiancolin** [ucb-bar/chipyard#775]
**Impact**:  other

**Description**
For large multi-core systems, our generators use a ton of memory and time duplicating work to produces modules that are later deduped in FIRRTL.  `CloneModuleAsRecord` applied to each unique tile-type could radically improve this. 

**What is a motivating example for changing the behavior?**
Less memory use and considerably faster elaboration times.

**Comment by jerryz123** [comment]
This is done with recent CloneTile support added to Rocketchip.
