### ISSUE TITLE
Clock and Reset IOCells

### ISSUE THREAD

**Issue by KPrabs106** [ucb-bar/chipyard#823]
**Impact**: rtl

**Tell us about your environment:**
*Chipyard Version:* 1.4.0

**What is the current behavior?**
IO Cells generated for clock and reset do not use IOCellKey, resulting in GenericDigitalInIOCell

**What is the expected behavior?**
Clock and reset IO cell generation should be using IOCellKey

**Other information**

I might have misunderstood how to use IOCellKey, but I think the following changes are needed:

https://github.com/ucb-bar/chipyard/blob/e3d23f10345cfafd9a2f4f8aacfe07c2746699f9/generators/chipyard/src/main/scala/Clocks.scala#L28

should be
`   
 val (reset_io, resetIOCell) = IOCell.generateIOFromSignal(async_reset_wire, "reset", p(IOCellKey),
`
and 
https://github.com/ucb-bar/chipyard/blob/e3d23f10345cfafd9a2f4f8aacfe07c2746699f9/generators/chipyard/src/main/scala/Clocks.scala#L97
should be
`
      val (clock_io, clockIOCell) = IOCell.generateIOFromSignal(clock_wire, "clock", p(IOCellKey))
`

**Comment by jerryz123** [comment]
Thanks for catching this. Can you open a PR against dev to fix it?

**Comment by jerryz123** [comment]
Fixed, thanks for the PR
