### ISSUE TITLE
JTAG TDO pin incorrect

### ISSUE THREAD

**Issue by bg193** [ucb-bar/chipyard#831]
**Impact**: rtl | software | unknown | other

**Tell us about your environment:**
*Chipyard Version:* 58076cf 

*OS:* Ubuntu 18.04
*Other:* 
make  CONFIG=RocketConfig TOP=ChipTop

**What is the current behavior?**
JTAG IOCell generate is incorrect，signal TDO is tristate pin. But now generate two output  pin jtag_TDO_data and jtag_TDO_driven

module ChipTop( // @[chipyard.TestHarness.RocketConfig.fir 281251:2]
  .......
  output        jtag_TDO_data, // @[chipyard.TestHarness.RocketConfig.fir 281253:4]
  output        jtag_TDO_driven, // @[chipyard.TestHarness.RocketConfig.fir 281253:4]
......

**What is the expected behavior?**
Generate one tristate pin  tdo_data it driven by tdo driven signal.

**Other information**

**Comment by jerryz123** [comment]
Resolved in #832
