### ISSUE TITLE
Linking libpthread.a report multi "undefined reference" error!

### ISSUE THREAD

**Issue by qqjinger** [ucb-bar/chipyard#842]
**Project:** chipyard
**compile cmd:** riscv64-unknown-linux-gnu-gcc *.c  -I. -L. -lm -lrt -lpthread -static
**Details:** when compiling c code with static pthread lib, I found multi error shown on cmd and one representative error is below:
/****************************************************/
riscv-tools-install/bin/../lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: riscv-tools-install/sysroot/usr/lib//libpthread.a(errno-loc.o): in function `__errno_location':
riscv-tools/riscv-gnu-toolchain/riscv-glibc/nptl/../csu/errno-loc.c:26: undefined reference to `errno'
riscv-tools-install/bin/../lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld: riscv-gnu-toolchain/riscv-glibc/nptl/../csu/errno-loc.c:26: undefined reference to `errno'
/****************************************************/
    As you can see, they are all about "undefined reference". The static thread lib, libpthread.a,  is generated by toolchain when installing with default build-toolchains.sh script. I use this libpthread.a for linking, but upper errors occur. Does libpthread.a depend on other libraries or objects? How should I resolve this problems?

**Comment by alan2031** [comment]
Hi，
  I met the same problem,did you solve it?Thanks!
