### ISSUE TITLE
scripts/ubuntu-req.sh not configured for Ubuntu 20.04

### ISSUE THREAD

**Issue by brendonsb** [ucb-bar/chipyard#857]
The Ubuntu requirements script specifies the apt package, python3.6. This package is not available in the current 20.04 repos casuing the script to fail at that point.

**Comment by hngenc** [comment]
I think this is an issue with [Chipyard](https://github.com/ucb-bar/chipyard) rather than with Gemmini. `scripts/ubuntu-req.sh` is outside the scope of our project.

**Comment by hngenc** [comment]
Oops, sorry, I was on the wrong project page :). Re-opening this

**Comment by alonamid** [comment]
Python 3.6 is the minimum requirement, not a "sole" requirement.  Ubuntu 20.04 includes python 3.8, which should satisfy the requirement without need to pull a special package (unlike Ubuntu 16.04 which is the earliest Ubuntu we support).

I agree that the `scripts/ubuntu-req.sh` script is not robust to multiple Ubuntu versions. We will happily accept a PR to make it more robust.

**Comment by abejgonzalez** [comment]
There is a current PR trying to see if the change is backwards compatible: #869

**Comment by abejgonzalez** [comment]
I think this is solved with #874. Closing for now. Feel free to re-open if there are still issues.
