### ISSUE TITLE
BootROM and maskROMs

### ISSUE THREAD

**Issue by bg193** [ucb-bar/chipyard#863]
What‘s the difference between the bootROM and maskROMs?

**Comment by abejgonzalez** [comment]
From my understanding, a MaskROM achieves better density for ASICs than a BootROM for larger images. However, the more obvious difference is that the BootROM is fully generated at elaboration time (i.e. the code image is directly added when you run the Chisel generator) while the MaskROM allows you to assign the code within it at a later point.
