### ISSUE TITLE
bintray is sunset

### ISSUE THREAD

**Issue by timsnyder-siv** [ucb-bar/chipyard#873]
**Impact**: other

**Tell us about your environment:**
*Chipyard Version:* 
*OS:* 
*Other:* 

**What is the current behavior?**
Anyone trying to use bintray.com to go get the sbt rpm will hit an error because bintray is no longer.  see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**What is the expected behavior?**
Instructions for installing prereqs should work and not hit errors.

**Other information**

I'm trying some updated instructions for centos in https://github.com/firesim/firesim/pull/764 that I got from https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html

**Comment by alonamid** [comment]
I believe this is addressed in #870 ?

**Comment by timsnyder-siv** [comment]
Yes.  It does look to be fixed in #870 .  Thanks @alonamid

**Comment by alonamid** [comment]
Fixed in #874 (since #870 was closed)
