### ISSUE TITLE
Bare metal (chipyard/sims/verilator/simulator-chipyard-LargeBoomConfig) cannot run binary files that depend on the linux glibc library

### ISSUE THREAD

**Issue by hz1490919302** [ucb-bar/chipyard#884]
Binary files that depend on the glibc library cannot run on bare metal because the glibc library needs the support of the Linux operating system. Bare metal can only run binary files that depend on the newlib library.
However, some benchmarks of SPEC2006 only support glibc, not newlib. Therefore, the compiled SPEC2006 cannot run on bare metal (**chipyard/sims/verilator/simulator-chipyard-LargeBoomConfig**). Is there any way to solve this problem? My ultimate goal is to obtain the corresponding processor debugging information of` ./simulator-chipyard-LargeBoomConfig +verbose spec2006.riscv.`

**Comment by jerryz123** [comment]
Those compiled SPEC binaries must be run with pk.

**Comment by hz1490919302** [comment]
Thank you for your reply.&nbsp;
I only know that spike pk can run binary files. How can the simulator-chipyard-LargeBoomConfig in the chipyard/sims/verilator directory be used in conjunction with pk?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ucb-bar/chipyard] Bare metal (chipyard/sims/verilator/simulator-chipyard-LargeBoomConfig) cannot run binary files that depend on the linux glibc library (#884)





 
Those compiled SPEC binaries must be run with pk.
