### ISSUE TITLE
Modelsim support

### ISSUE THREAD

**Issue by galsanka** [ucb-bar/chipyard#915]
**Impact**: software

**Description**

Hello,

We would like to use the Chipyard framework with the ModelSim simulator. I was only able to find Verilator and VCS setups. Do you have support for ModelSim? If not, can you please add the support for ModelSim in the framework?

Thank you

**Comment by alonamid** [comment]
As far as I know, the current main Chipyard maintainers and developers do not use ModelSim, and therefore Chipyard currently does not have support for modelsim. However, I believe that if you follow the Makefile structures in `chipyard/sims/vcs` and `chipyard/sims/verilator`, you should be able to follow their structure to add support for ModelSim, and we will happily accept a PR for such support.
