### ISSUE TITLE
failed when make default with VCS

### ISSUE THREAD

**Issue by SK-Xi** [ucb-bar/chipyard#949]
My environment:
OS: Ubuntu 20.04
VCS-MX  O-2018.09-SP2_full64
gcc-7.5.0 & g++-7.5.0
chipyard branch master b5d0131

When I try make, it failed when compiling Dramsim2.cc.(probably)
And when I try the Verilator, there is the similar problem.
Wondering how to fix it, thank you.
Here is the log:
`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/mm.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/mm_dramsim2.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/remote_bitbang.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/SimDRAM.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/SimJTAG.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/SimSerial.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/SimUART.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/testchip_tsi.cc`

`g++ -w  -pipe -fPIC -std=c++11 -I/home/work/chipyard/riscv-tools-install/include -I/home/work/chipyard/tools/DRAMSim2 -I/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig -O3 -I/opt/synopsys/vcs-mx/O-2018.09-SP2/include    -c /home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/uart.cc`

`cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C
/usr/bin/ld: mm_dramsim2.o: in function `mm_dramsim2_t::init(unsigned long, int, int)':
mm_dramsim2.cc:(.text+0x1d0a): undefined reference to `DRAMSim::getMemorySystemInstance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'`

`collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:110: product_timestamp] Error 1
make[1]: Leaving directory '/home/work/chipyard/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/chipyard.TestHarness.RocketConfig'
Make exited with status 2
make: *** [Makefile:72：/home/work/chipyard/sims/vcs/simv-chipyard-RocketConfig] error 2
`

Not familiar with github, may look bad, sorry for it.

**Comment by jerryz123** [comment]
Can you try
`cd tools/DRAMSim2 && make clean`
And then in the verilator or vcs dir run
`make dramsim_lib`
