### ISSUE TITLE
What are the recommended specs (or what do you run) for using Chipyard?

### ISSUE THREAD

**Issue by michael-etzkorn** [ucb-bar/chipyard#975]
I've seen that having at least 6.5 GB of RAM is recommended for making one of the configs. If I wanted to set up a new server for running Chipyard, what would be a good baseline for hardware requirements?

**Comment by lsteveol** [comment]
It really depends on the size of the config. In my experience the number of diplomatic nodes generally dominates the memory usage. For example, I had a custom NoC configuration (which was external to chipyard) consisting of several Xbars/APB/AXI ports. I needed about 23GB of RAM to build.
