### ISSUE TITLE
"key not found: ExampleTop" at: project-template-old

### ISSUE THREAD

**Issue by nachoge98** [ucb-bar/chipyard#981]
**Environment:**
*Chipyard Version:* project-template-old
*OS:* Ubuntu 20.04.3 LTS

**What is the current behavior?**
I'm trying to run: "make CONFIG=PWMConfig" as stated in the README, but it's giving the following attached error.

I obtain the same error when I try any other configuration, for example: "make CONFIG=SimBlockDeviceConfig"

**What is the expected behavior?**
Generate the executable: "simulator-example-PWMConfig".
Or any other one with a different configuration from the "DefaultExampleConfig".

**Other information**
[info] Running barstools.tapeout.transforms.GenerateTop -o /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.top.v -i /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.fir --syn-top ExampleTop --harness-top TestHarness -faf /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.anno.json -tsaof /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.top.anno.json -tsf /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.top.fir --infer-rw --repl-seq-mem -c:TestHarness:-o:/home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.mems.conf -td /home/igsaga/chipyard/verisim/generated-src
[error] (run-main-0) java.util.NoSuchElementException: key not found: ExampleTop
[error] java.util.NoSuchElementException: key not found: ExampleTop
[error]         at scala.collection.MapLike.default(MapLike.scala:232)
[error]         at scala.collection.MapLike.default$(MapLike.scala:231)
[error]         at scala.collection.AbstractMap.default(Map.scala:59)
[error]         at scala.collection.MapLike.apply(MapLike.scala:141)
[error]         at scala.collection.MapLike.apply$(MapLike.scala:140)
[error]         at scala.collection.AbstractMap.apply(Map.scala:59)
[error]         at barstools.tapeout.transforms.RemoveUnusedModules.execute(RemoveUnusedModules.scala:48)
[error]         at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:199)
[error]         at firrtl.Utils$.time(Utils.scala:186)
[error]         at firrtl.Transform.runTransform(Compiler.scala:199)
[error]         at firrtl.Compiler.$anonfun$compile$2(Compiler.scala:457)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 30 s, completed Sep 15, 2021 12:01:14 PM
make: *** [/home/igsaga/chipyard/Makefrag:63: /home/igsaga/chipyard/verisim/generated-src/example.TestHarness.PWMConfig.top.v] Error 1

**Comment by abejgonzalez** [comment]
We don't support that branch anymore. You should use the main Chipyard `master` branch.
